sprite $CloudSecurityCommandCenter [70x70/4z] {
xPS7ZiGm30DD_l_FruiZU685n-jBj8rMcL1ka4TJDyaxDI3kA0AnjkK4pBYh2CIAK1o1i1dvYjXA0AC8nLSLWLXDYfx3WcfR4Bt6HGdxePtemfmY_ChXIUSO
eTFoh3CALxk846R35_jMX6A0NAIeCMAB6AMRA8BeAjz44OVx53NZdY1KgDvU4r6qsK3s_EB9bZDJgYyHHQDv3la36bzAKOII6PVLYDCS8L0yrHEohfsgpRaD
7bVvE1e09-zWHX04EavmyOVE6LF66AtmNt3kWXKs0nGOMZ0Ze31aFsPgM65CfJ044rGfdBF777vLjJhCcT9ixBpIhgz3Cts5-jq4PYGe6WdC8CbzANHN2vZ9
tM5P0KYx9eq0Pg3w78r_e7i
}

sprite $CloudSecurityCommandCenterParticipant [50x50/4z] {
pTK5RWHH40FHTjt_q144MgeXXxtilsyOvl-7awG5G0tWUmIKX6yNr83KWakG0LokH1C3tA-u1zQqHE8vht6mmDNrE8z5Ml7MOO5_hYeIuIqMshAUXF-2n9vv
deazQGc2ekLNIZ6rUB8UGQikGTQd9kgJnfDuk0lFJn7FPF2Fqqh7hcQXJaA3v_Fr64-k30OMR05OcEHD2Aoak2PMrzsTj62c5rE2Ndp_tJdJaZb9ECxyTbu
}


!define CloudSecurityCommandCenter(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSecurityCommandCenter, resource)
!define CloudSecurityCommandCenter(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSecurityCommandCenter, resource)
!define CloudSecurityCommandCenterParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudSecurityCommandCenterParticipant, CloudSecurityCommandCenterParticipant)
!define CloudSecurityCommandCenterParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudSecurityCommandCenterParticipant, CloudSecurityCommandCenterParticipant)
