sprite $CloudSecurityScanner [70x70/16z] {
xTS5aXmn343HRrRGzpzjQ7UcGLAtKwLmVi6I_TgmD7En_ybzAqO08n6Ch1Q0X2aIW8Gf4eA8YqGm4i78Br9a0ObNe7dCEj81okE3DZnco5K50CRptMuhSjFW
PJa9V4PD4Xr0WlpoxeAIi9YNTRo8sm0NQM0o5IZdEnkECe3gdB9UYpXB0PBO0IyQikKguWMaSdgCYQJZVdhhifK1jLPp9Vkbg4cWb_fHAHo6yUXwknhPpmB5
56YYkbA6eNJ8OkGhcQsoZKZVfx0hwOFnI_ivQLtnV-IaijKkTpGDPeYuTzIWB2XjTmbLBoL3Nr06SFvLIRtxhbCCC8xdb4HkbO_MBn4le1k8jnYxRZtXpRIO
2lXBQSPIdCLenl_2nsapGuzkEGz7dqhn65xo4Pz9Fg8Ldo7rJLb0fgWoAb_n6KaBobIAhcVs9JLWJCtuBInbXSbGHHNqFsO4CsEK22RoDOakHdaJWSmPetoC
GDON4_dQtYy0MMFcFz1d
}

GCPEntityColoring(CloudSecurityScanner)
!define CloudSecurityScanner(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSecurityScanner, CloudSecurityScanner)
!define CloudSecurityScanner(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSecurityScanner, CloudSecurityScanner)
