sprite $CloudResourceManager [70x70/16z] {
xTS5SiH044DH6Lj1t_-qOUmQZTifXVSN1lODh74hTehxLGm3GmV3QWR4fj20s1HQ44h4mT31qACu67wRmZAo08WYe_vlmcDhIM6p0QzDYkaZWTHuN5dHAdfC
OpjK2rEX5RmshB7WJSn9X7aDGqUXLlAExYliA7ngxYXCY5QYfrnNbRMdC2DPcSM-f7OKvAc08gMypcR4nnJHjof3g7sfx-xOW0yhqJZFvmFArBgwwQdqhdDC
pJtbMYs9gLKjI5zqXS96iKccSP6TW4bEHP-GyZVvkg2P2O2OdRW9iB3101Q1b9bLtXstFMPuEGawHsrIvBq-S5_zTgzFxa4X9OKno1qX6QPdAGEpUHG7itaK
1-Dv9r5vbBCZYCwZN3kG-cISx_Ow0r9Zjd_GBG
}

GCPEntityColoring(CloudResourceManager)
!define CloudResourceManager(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudResourceManager, CloudResourceManager)
!define CloudResourceManager(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudResourceManager, CloudResourceManager)
