sprite $CloudSecurityCommandCenter [70x70/16z] {
xTO5SWDH38DXBLf5t_-qnT0RFpdaSl-1y3SAhv_OVppUAKO1mmg6B61OerGm_7I59GWbKi6mWk4NAJmHCO0aLooNAmkmLO1HCJao0OSACDWnnjXc0z0exrck
X9S3NGMO4oQy7581fjCKv0fCCBn2iHA50OaADmrQuJ5b3TTgXKenUNLag9ILRL9vp9JDUp2Eo-QSKjX1s2273vGAjH9tpLB9Mz0m5pQKAFZKBSuimwRXY29V
qisOUE4qXOTtdiDdP-uWwSUkRTPJt1yfxZugF2BPc5bTsNRZVMQ8x--2P4e-1XWE337bqHKpYTzTCKKe58f056DzPHAAOjQUCWX4Abmw2fMYcJKe6j4AhLKc
nioFCnmEb6iExFBZkg9Zp0h6QvGAnYiKLzKeDnM8UutoM86ubo3kDOeN8ASn_WTw1W
}

GCPEntityColoring(CloudSecurityCommandCenter)
!define CloudSecurityCommandCenter(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSecurityCommandCenter, CloudSecurityCommandCenter)
!define CloudSecurityCommandCenter(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSecurityCommandCenter, CloudSecurityCommandCenter)
