sprite $CloudResourceManager [70x70/4z] {
xPOvSaKn40AdkV-X7NbL3UALSUHFE8LQQDU4UWdT542Kg08Hr-4KmYXL1I8g55KWmanj8OnKm52XwAag456Xg08vm-2Sf64kDY8CTqz0YLRWXd4C7nb3cLNi
LfiJSB7PS_xiUu8UPIZttDhgEjfGerYtVarX1aiXc1Vfe-fd5q_1KJxI51-RlwTmeP3CYvRgsSHJs2aijKEuNQUpk4Pdk-TCCSHl54poKooK7JBXK4s73cCg
vkIQdlr2-32pGCp1jHYILstazu5vX4FCi1lqxCymuGT6pXVVG-YvAFth2c5A_zq6PXeKfe6PJHIYr1u-SeXJXp8Lo11ERG5Z0I67-GTw0m
}

sprite $CloudResourceManagerParticipant [50x50/4z] {
pTK5ZaD1609WuFvttgqhFnFgH2haUpg2tu-6C0AV27nU8vHZmCk5QY3MGWOq9w7fyqby6GYdPXJXcNYIXobDwuz2ZBMCE7ptFOrW51e5_SrBuQfAGIj48_gf
bWMiaBdpAEA0T4ztzVZlfqterySmjJk9pZ5jFiaqGMX8180yCKqW81BernAWNgz0hSCdrrsm1K0lK89Ul7vt9bg28PGFFfr_
}


!define CloudResourceManager(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudResourceManager, resource)
!define CloudResourceManager(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudResourceManager, resource)
!define CloudResourceManagerParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudResourceManagerParticipant, CloudResourceManagerParticipant)
!define CloudResourceManagerParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudResourceManagerParticipant, CloudResourceManagerParticipant)
