sprite $CloudSecurityScanner [70x70/4z] {
xPS7TiC024EHxd_dxdf-KtYFhYHgi_57o3kAUaZ-IWM8Ang1MFrn-cPSrGZ46g5u168bqGwOiGSm6g6ugn68DK9n4yAXMQrejUqZwT9CnRcMjsACQa7wM9zQ
KHBb-rioWs4ovb2WIug2CGAASmY9A8iPSIrZbXV82qfHP9yXUtEIW78cP_ES5gA-2A6j8HrNYtjq3Di2hhy8NrC45A6PZ1B1PWpwEnGXvhodAQM4auskcgwN
HQXCQ4MqmIGKdo0m4ACZGh35CwM-Lt2BpauDup84aqci4BarKoHMJdpXiLWC4Hs-6GE5i6KA6pGW_BDsTAW22eO6oY7Sfa0HLt1HtR2SAB7Il0uImy5CJqFN
knEOcA0e9Z0nSMkZeNkr0JEpzx2i0KXv9iK09a1TZk8Ez0m
}

sprite $CloudSecurityScannerParticipant [50x50/4z] {
pTK5ja8n40FG9FlVyrUaavCf31wqScl8m-T7JTY2FcCWFKP8GwA72us1E1PoC9o4UKpsaxIhuFyhdN2p32rZsXIzaOvT0d2jGpDODb_RBKN80O6q_xNUjhqK
o7AcMaiA9Q0SASDEQpUW4kq4rgz34c8Gs0gPq4M1IgYmgbxGlWpC0gbG0If0Bf7DL-sgRuc3Pf8y1R4dp5C0D59Q7UHANu0B9oLicgJEz0qUIllPgH3MQjxv
lmjE0J0N68AvUFpLcPWID67N_zNv1W
}


!define CloudSecurityScanner(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSecurityScanner, resource)
!define CloudSecurityScanner(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSecurityScanner, resource)
!define CloudSecurityScanner_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSecurityScanner, new_resource)
!define CloudSecurityScanner_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSecurityScanner, new_resource)
!define CloudSecurityScanner_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSecurityScanner, modified_resource)
!define CloudSecurityScanner_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSecurityScanner, modified_resource)
!define CloudSecurityScanner_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSecurityScanner, deleted_resource)
!define CloudSecurityScanner_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSecurityScanner, deleted_resource)
!define CloudSecurityScannerParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudSecurityScannerParticipant, CloudSecurityScannerParticipant)
!define CloudSecurityScannerParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudSecurityScannerParticipant, CloudSecurityScannerParticipant)
