sprite $KeyManagementService [70x70/16z] {
xTQ7LWGX38NX45WI-_i_hUtQsBadp1hi_gVOFpDXozpix3-VbpPGMa5f12MGvOedaEMAPn6KHb1QGGbakU8d85RpYibz9MBco46UipsCEQaA1e7JvuflA_9G
U_CvMr28zEF_t-GX3HLkq6yQOH1RgPBpOhXH1SCtv-b6SOP0yJTPFvh76HChYcNC5G-KAiW2nO44YeZWT2BbUg9qJD5YnO5m1Py2YnMF5SF3LxZ2utlHNhAA
2VAKuWuag_ZuKjVtRhT7IjkhE0w6Atg2eiFhNHdNH5_mc2A1qgXoFJsaCbaBVz6rDt-eEYX2bBERWM6_ErwHiGi2GeTHgWX_NGY68NjfmIXqc5Uc51rmYd2c
aZy0mfJecdJxhKeHhd06QwPAl1eP4M58hE3l3ewKJs8tSwR0WI7jlRTa9g_v347XBPbbRrMBLESjklUcPH6KHj0QvIoBe3NATHP1QGIb5PH6q0hZvtS7
}

GCPEntityColoring(KeyManagementService)
!define KeyManagementService(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, KeyManagementService, KeyManagementService)
!define KeyManagementService(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, KeyManagementService, KeyManagementService)
