sprite $CloudToolsforVisualStudio [70x70/4z] {
xPW5RWHH3CNYT_yxbxdvIdPgOVS95iVoPwXbxY5JQausKI1XB8uWasqKI50eKI1d6H919X4mA9JS6WKI54eKI6YgLf1910mA9LUZG892oGgob-5Fkei_x36T
GTCrFnvXHVduhkkOtGDxoBi3ZGpjLyLN2emoWyhtzvmmr52rUSqWCwYGj68pXTifZDMogPWQccXNBxMI6NelDSWiE-zPXWv20_76KLScZcEQ7ZBF7FDKDcFs
_o7NWxG623BIscXWog1G1gQCRH3IlawGaVQx1gOC2cLWoZZQ89tL11df36jWoZYMKmB6kFIW_a4U0G
}

GCPEntityColoring(CloudToolsforVisualStudio)
!define CloudToolsforVisualStudio(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudToolsforVisualStudio, CloudToolsforVisualStudio)
!define CloudToolsforVisualStudio(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudToolsforVisualStudio, CloudToolsforVisualStudio)
