sprite $CloudBuild [70x70/4z] {
xTO5ZWD144DHVz__piizYmLHBDnO47AUgeUrp2DuYkPuamXYnkK4Xl4s4SH457T8O1Zim31sW26Y-DP441DHl4UCM0z3MzmECzHOCOmT5ifcrKnCP-nhTnpU
3OAgK5QPLgilARlpBgQhLZgskGpPzjM4hQAFFvuEb-rg_SM8Vvu0qbyApSxZ6E9ZBkgzxKhHbpU7AXGMYisWs1j5zoiseyAaO6jKD2cs5Wgzues2r2Z-EagZ
T6SqFuvULKf_hkieg-j8eLpECGf5eoADDmEqOsWluILlIiLDrSsFDatFmmthgzAt-jlqfNITcV5HkiAic0-5wkSTOzcmVfZ2juVGSrrWcD3pRe9HGa49HbL8
Z28bHf588596KG1Phma568sP7VGFyWm
}

sprite $CloudBuildParticipant [50x50/4z] {
pTLNSi0m30FHnTx_pkbLGsJCTFx2p-eI_xyibGfwhO5-Zz0byTk5Qs3MmXCi6yaGvyD6vj1Eqf8gUkEPepQ-7hO6QZmshDBYl6jM0wXF9ffJ7Bzunw8UNqoD
QW2UcxaW8W02SWfD4pPX4P4YACAjKAfW468070I383u7Z89vZwJikoAWd9BGoGWSZyqXhXzEIzA9vVptkqJGBh1K1SJrnRjj0h85i1SimLvy_-iSjeHISIv-
ksu1
}


!define CloudBuild(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudBuild, resource)
!define CloudBuild(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudBuild, resource)
!define CloudBuild_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudBuild, new_resource)
!define CloudBuild_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudBuild, new_resource)
!define CloudBuild_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudBuild, modified_resource)
!define CloudBuild_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudBuild, modified_resource)
!define CloudBuild_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudBuild, deleted_resource)
!define CloudBuild_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudBuild, deleted_resource)
!define CloudBuildParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudBuildParticipant, CloudBuildParticipant)
!define CloudBuildParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudBuildParticipant, CloudBuildParticipant)
