sprite $CloudScheduler [70x70/4z] {
pPO7aW9130FT_l-VBwVPclQ9Z2eGHZGowpMkFw9YkPbMJ6wcsp2vcMx3v6Qw5HERwPJYRWoIOnm2V1u168O90lH181Y3q7k1O42oYTXW5eZaC0xylW6Rercm
UFbvRa4Si_ae7WJmgg0vtkNWLnOaJXs48CGWNIqCzOX166eRZwb9kD4XCyOXEpxipSBtb63ZnT_sC_T3zhCpKpgWo5YGA5d73fEjXBB1e5KIKDh2mDZuj8GH
IYMKDagVH64j2HORvr4wfdX9vrCOAVNq5Feq2lDWooaU9Bz66YJl5v_5OU-oeo0G_Mvq_3d4AGX32X9AaqFuV-uAGUQkXb78l3P79I4GVvSH4l_5WbGZ4DqP
O9F38Rvw0C1PQn1dxr9LP-rrZibtJBUu2VmysA_rpDBauan86APF4XT5oVOtO6JyEeTwc4OtooaQ1VIUZXP1x5u4OEC5wpegqzns5GhgMVKA
}

GCPEntityColoring(CloudScheduler)
!define CloudScheduler(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudScheduler, CloudScheduler)
!define CloudScheduler(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudScheduler, CloudScheduler)
