sprite $CloudCode [70x70/4z] {
xLV13aCn21B-_wDt7GaIct3RkAc6ehxNjdF47o0pS23X0MYGaDToCj0W8L5XOIOfYE43afI26B90WmOBo08Ddz6GGg8XXNHI2cB80WrS2eoLM9OC62lGRAs3
Mg71CGorefYm1embI59KPrADG2BbvZaW1pmBV3AC4gmLpNWQF-AbktPPx_kYWNSg85BiibwWGXs-1RvPuHzBuy0-y9ofEBCGKX6l5GqLaExorbqpDXagZvCU
KW5PbeUlpZeXBU3X3_0qCYepViNRFvsJCmt4IgdSOn0hxueh3Oor5iyb36CfEgTQuuHbyRJtOkwet89QDxA2cD9DjK7Jki4Nn5HUDgrNLa5CwVNPe9cCgvGC
d4aoK239032_WGy
}

sprite $CloudCodeParticipant [50x50/4z] {
lPO7RiL0448DtF_CwGdHCcj-Hst4w0dZVhnSr22U0REs2BWLIiAbAM91sZ7rus9HZUWXh2eHdI2x2b0GN4OW8feK4LNOHDY8rKpO6NSxqrDkvs1vYZKu8FAK
vHMbxNrCQtqT64hB-wmFJANFlFyPYggZ1reAm9vSVLbhkUO_df7bx4fvpINI2DogNtFveizLFT48VBD7LK-MDDoAhkh9sZnHKapnsF92xTyCwgz5DgI_i5JV
lEX8VLEh4MW8ZXh2U51g21KHBOJA5Xt9Y8uueHD6hlwJURdU0G
}


!define CloudCode(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudCode, resource)
!define CloudCode(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudCode, resource)
!define CloudCode_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudCode, new_resource)
!define CloudCode_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudCode, new_resource)
!define CloudCode_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudCode, modified_resource)
!define CloudCode_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudCode, modified_resource)
!define CloudCode_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudCode, deleted_resource)
!define CloudCode_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudCode, deleted_resource)
!define CloudCodeParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudCodeParticipant, CloudCodeParticipant)
!define CloudCodeParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudCodeParticipant, CloudCodeParticipant)
