sprite $ContainerRegistry [70x70/4z] {
xTS5TiGm48DX_Rh_dSiGloZaLRbw49ZqyzXTiaxcF_WeEexFf8AOm-aKcl7PL11JKLn1pCxI5fgn2mmLnLTJGKn5SK8ApU2P7BR21CEw7FzcNmd5g8WT9YrQ
c5jecorblCUYd9xUHOXNh9ydB-rmPpNGTZEhzGhz3cCxCFuMYWCoeI1nksB9MHaTUrVXK372GGd92WhM1MKvb_4yAsmfUWdZ6cT5HufEAHGKf88YYPiLIL97
KL3UQWpdKT66WXVFB-oeeCG4UBUQlus2l5VZy3iW8uHxeU0zXGJdWTbGBdx5cgW4DoXNWngC6Z-3AFskApHJ-htRODHGK8DHOsj3QQzMQAQqXsqmQcpBKO5H
o5K7_O7S0m
}

GCPEntityColoring(ContainerRegistry)
!define ContainerRegistry(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, ContainerRegistry, ContainerRegistry)
!define ContainerRegistry(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, ContainerRegistry, ContainerRegistry)
