sprite $BigQuery [70x70/4z] {
xPT7bWCn44A1-zzvyhWpecLsDXk7glT5AGkXtg962Y1AL868mt8APfIg0X4h53b8mGobWXcfW665ehkgGCGAHHOoRuQQaR4oZs65OcedQJ09X4Ep75AOs1qb
PCD87zuqOFAibLs48yorqKFoNSeI233EYldl4E08lymwqpEweYnVEJHZ2ree2pjJdm8Wep2Z07GKsxivXId5pIu_7LUKo_bY0lmDy46nAy16jYFDfvOZ0uZV
6XYqHtZCme7937RKWrnMScPTZ4LoD1BO5-OQodHi4PCO0qafeXy0pGYDQn1Bzxg2cT9zju51Wq8qC6WyRLXwgnNCmAb3GG4IrqGKC1OGSeWNq2S
}

sprite $BigQueryParticipant [50x50/4z] {
pTG53aCn38DXE_U_ynYZ_DKyjcZAsrTkzVyfY15m471o0I0ZzNPHCIZ7eZe8Et5Ls4bLI1oBUSncmctHv8SoZPV0kGHagBNVNG1WKikAMVI_IDGapU8gtCaa
f8NGGaYF23S1IzCBFebXTQdYacWQs8YXGJXNfgyM4BoVT0Lr_I09BawFxM5j10JNNoGOfqJf4-SNtrqv1L8k581094Ifi58Y22snlfqj
}


!define BigQuery(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, BigQuery, resource)
!define BigQuery(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, BigQuery, resource)
!define BigQuery_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, BigQuery, new_resource)
!define BigQuery_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, BigQuery, new_resource)
!define BigQuery_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, BigQuery, modified_resource)
!define BigQuery_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, BigQuery, modified_resource)
!define BigQuery_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, BigQuery, deleted_resource)
!define BigQuery_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, BigQuery, deleted_resource)
!define BigQueryParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, BigQueryParticipant, BigQueryParticipant)
!define BigQueryParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, BigQueryParticipant, BigQueryParticipant)
