sprite $CloudDatalab [70x70/4z] {
xPO5aWH140AJ-l-Vprre63dT35cfYMmO9-I2PWLh9k4GoQYlquUPb5RITvgSIjA7qJJOA3bD57rgRwAOZ4KVeMO7Jqyb4OHXj5Wo2pEPnMlaofXv5WKOIzO7
ZKNEafDAiZ0cj6wv_x8CixEqcVSMm_rK_LdPMmJQRvdLEBDePT6pRSTv-KfNyrn4mGckTHJTuZM4DqfvYroKy4uZ22JSuzQJEo6ZCDKp4MGiV1ObV5AO6H0-
-_JvJ33F5divyOW-Zg8aYymmRmH1c5oIXwaViIBfasvWUllAEMQX79tqNeUEaC0n5dh9VeiuGiDdg8ooFmmS40R7CHRsI_9EuW0D0Gg2_7ck0G
}

sprite $CloudDatalabParticipant [50x50/4z] {
pPL7TaD108EGxd_ex58PlRYRtHICV-VzwO5CmPc2Sn-Z6n7kRXIsy7Sc5niLmV58-XVhxeHChmIHHaSYf8O9cqnZHCxn-58kDZpUTYmzs6YEWYjEI0kumI5n
Zg29QN2Q2g2hY22vTGcXuGiH-9luTfE0tRmh0NR7HHk-o8ZOca_3IEmVsYlz3nBV12wCm8KHuC88bofSR3p-wnmkLS197PxD1m
}


GCPEntityColoring(CloudDatalab)
!define CloudDatalab(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudDatalab, CloudDatalab)
!define CloudDatalab(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudDatalab, CloudDatalab)
!define CloudDatalabParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudDatalabParticipant, CloudDatalabParticipant)
!define CloudDatalabParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudDatalabParticipant, CloudDatalabParticipant)
