sprite $CloudDataprep [70x70/4z] {
xTT5Okum00FX6Tt_pW_B9F-Dkcgr2tr9pEOmFp4jzEGa4oJMtnbyJ4upGU94oGI9fMWlVamoO9mekJKJ94wKJ91uNhJ0ySUaAvrnegGhdKbND6_5fjnTA7VL
ouhrDZykMaYWAYbN3vLyU560N5CUgwMtAO2Kz5i4hok1Slwezyix27XrE8Fxhy5SKlolv4WnRqGK_dkUA9GM02VAfAQ5WG9uMG6WlA7NxqStYEA1SiluqgUs
2qeREGImAa8VCwl2OvpCQcmKFgcmKAGpNQ4lWteShUi67pDQxouO5eei61PR6xzuhuOB13OA4mHp4Xamr7H7la5-0m
}

GCPEntityColoring(CloudDataprep)
!define CloudDataprep(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudDataprep, CloudDataprep)
!define CloudDataprep(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudDataprep, CloudDataprep)
