sprite $CloudPubSub [70x70/4z] {
xPO7RiKm5CEeT_z35wFRaIsZmkpNdx45WjaXp2kQKpXdabGWe-Fg56GcJGKogb2c0l4ocfjubG965ShSfW8PLIYJGmGea_75O3PGEKndAhgYJ4xncB4v5HHH
T9YV3KJIzzgtSI-ZH_u3nPU1Pqijb5qR9rcWVBbejDHNZDlk3rlK79yoHws-J5RY6aWk8UTMU0MPo_Gf2YcgkB0r-KRPSZPx6j1yG0JONIeudEtVVm3NbuTe
6VHzHv61c_uVANV3UXuNTlpU71JULMKDL_xQ2k_uEhG2oBR63OMCuY59Rqn4YD652cZkez9pNK6czBpRmD2WY0O65pLKeA42Qa2WGw42GH54533Ov1pn3_86
}

GCPEntityColoring(CloudPubSub)
!define CloudPubSub(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudPubSub, CloudPubSub)
!define CloudPubSub(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudPubSub, CloudPubSub)
