sprite $CloudDataCatalog [70x70/16z] {
xPT7OkWm24G5eep-_U_xcnFIGCRHDc_dDiP3aJoQ_43CiuQPEXhJ75jCxdK4wmxedSmCaGCPyjN1v_vxLW_R1SDOFR09XcnrSJx9Jr0QpBxwO9w54WOVX190
KciLwn6M6JnzFGD2IIZhASxz1jgtKx-1-kqawpiOTHi8hePMjaat6Zn83BcGqxvgSQ7yMamNNzffMxLm_OkvH3NP_nEesqcGs4z4Orgec0mYOYyDPgzAWT-f
pFo5aDfQvq5JvCCNYGWbWyovgbh8TJg64Gd-HvZS3Qd6fCLBOPC6iI92p8CHf7CiJhjEyNTpaf5uI9wxeYi0FWJfoUsCLTdIlG0PivWSPFtpcgj0YNCLafMf
4F8c15JyeuI8mv4lAfggG2SDVgVplozPKOnnziradXvzHL5zQTafwi5C6YdE9sjSOZzHYTaWE57Hrojse08krw9mbotSBMxLQdX7OaaS4LsUQT3Tu1M36Lv4
3IxozTFbRb43bl5Bc4gi2wXNajoqy9JD0Ikw4pDPxDExY9afkI7TJ-b-Sy6-kLeR7AcwI5-YxRqXBif0ys3wG0utghcrKUtFjys7Mpkbiv-9wENpO6HKa9vO
6x2VM1i8pgpj6nnLU_XDAAtj_vhyYlni837FmNzSURIW7QFF3ty
}

GCPEntityColoring(CloudDataCatalog)
!define CloudDataCatalog(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudDataCatalog, CloudDataCatalog)
!define CloudDataCatalog(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudDataCatalog, CloudDataCatalog)
