sprite $CloudComposer [70x70/4z] {
xTStWW9H40FHakv_w4qMo1enBJmLVlEmumZx9LyhG9nKGIp6v2p6d5P1h8hY2c8DNstXpTW5HXN5jrP1h8hY2c8DN-tYpGpp-J9L51zKF4tcYYgAfxbSKV8h
fol0cJ8l6QTEYW2We4nhlLO4sYi65nGLbFpdUuYYKO7i4z5HL5041GNGMW6Wex1KmlFBh8Y1YHLEQN4SYNCBXKjAbGc1Zi91XOOY1YQEncsGIlTrXJTJkjzj
C3GKqM1eFDhepizgg850Hw6282U90WEmTSGNz0S
}

sprite $CloudComposerParticipant [50x50/4z] {
pTM55SH0409GeF-Up_s6UKkSkFpe2euVcT02dnX8omWf95fSA0PYB5I0v2QKmfiqByZo66EXGQ4Az8AnaF-oxG4Mvzxdxh0Y8K2h2p4K_LUg1PhYjfX0A315
816--3X1LtQjC9N62poJ2mmAb8BNVCoDW4Q2j8dZp7ONJ06G2uGW5yltpaHAO4BLmTOv0m
}


!define CloudComposer(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudComposer, resource)
!define CloudComposer(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudComposer, resource)
!define CloudComposerParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudComposerParticipant, CloudComposerParticipant)
!define CloudComposerParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudComposerParticipant, CloudComposerParticipant)
