sprite $Genomics [70x70/16z] {
xTV7MIqm44DXEOvU0FTVBJbZY_aksi4fu5yuUoNxZL-NCGmC7Gop6H2RGWDYKsX1Q458Zq83ObDeG6mABqD2Cy5t1S1D0AfI-3xi8e5Fka1C2alZfW8C7Xb-
ex0ej22aLXZlnwH8vMJWjM079CD33MzYmLtSToqK0lCvCW2CyyWmMmiU4ugrWcP0n83amrsLsTI41qMvqHqrc50C2QMWyqqXzwCQrk0eJm5GohLG9l4cUJG8
XUHuwgpyMOffnN1APRlsdBjdPGQJwLkjx0zHfQpDaSk1JKqWQplBs3IOl-xhOH-FAP75YuhbO3olGu_YO9P7SJ2UFyafZ_B7WDpbKQxpY2gDw3pACY0vPls0
RW4
}

GCPEntityColoring(Genomics)
!define Genomics(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Genomics, Genomics)
!define Genomics(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Genomics, Genomics)
