sprite $CloudStorage [70x70/4z] {
xTWt4i9050JHt_U_D24UfffPdDInwYLQFwlZCa_W8Hua30qH913Xa9OPte420mK62WmK65mh52Wm-3pIL_18Nw62aApIAVFoUBoD64OigWrbRYWiKWIpAxjo
5XGK0A-Sh1rUELyyf78vwvLo_OLGk95GxZE5jUwx5B6L18gwmQpPgETxbD9Pgi5CM_7CzvpWwtSIpxJlQfwPEqd3E-MxlNScAJQyKtqBoik50m
}

sprite $CloudStorageParticipant [50x50/4z] {
xTOf0iGm30D0pVy_lRZ8Le-W5VQqkPEy49UqzJE2na1bw8WfDQ06r81Ur80QS5TeSa-KWv6adA9aiwgV2IkHIVo5lI19q0cm5130IhZaZR5AAV9Gc84J9qDB
qekMV7yR92r9IvAEfB_FItBdNTAOZ1dAVm
}


!define CloudStorage(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudStorage, resource)
!define CloudStorage(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudStorage, resource)
!define CloudStorage_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudStorage, new_resource)
!define CloudStorage_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudStorage, new_resource)
!define CloudStorage_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudStorage, modified_resource)
!define CloudStorage_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudStorage, modified_resource)
!define CloudStorage_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudStorage, deleted_resource)
!define CloudStorage_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudStorage, deleted_resource)
!define CloudStorageParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudStorageParticipant, CloudStorageParticipant)
!define CloudStorageParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudStorageParticipant, CloudStorageParticipant)
