sprite $FirebasePerformanceMonitoring [70x70/4z] {
pTP7OiCm44FHZ_jVEjjX2a68Y6tOwiEdNh2Hn4NqFGKYXxHBODmwEaW1yOwEao6veom1aZBA4o098nKOlLMHGN96_wxO0eimOgkCuPmC0QFOpGHNU-YpBRQw
Pvo-3Z85rcQmP_Q802GMXLZHs9JjncoHdnkGAZ0GvdQTAQDyA02F5M2PSQACvWEPCu9N-UQs_tW5esWWYIB0JURNxXhUe4I8CAK0m4E5OQpJwREEDHA14dz1
vafop1KZN7-6bjxJ2ICvnKE-HZUXmT1Mg21GGQWWq56e8511e890mSWSA32u1CODmsaY8tV8Sovy0G
}

sprite $FirebasePerformanceMonitoringParticipant [50x50/4z] {
lTO50iD020LHvlw7hdjXib3vRPHzSOiYGAo6fpJRRoEA66WPD0BSE702JG9Dmiy40foK5H7PRAkr3di5V87lG1TPWCVUjZWFpgCfIS23U2GgW5WLyF0WEO-R
Y6T1AdWH-LdvjuWNaOxwiNgFYuJ4ceXZHBoIE6VnKdn90YR2I5v7J5v4IE-1HPB1Cx5B9c-3kOW6Q939kxPb9jyCBJFwzd7apVS
}


GCPEntityColoring(FirebasePerformanceMonitoring)
!define FirebasePerformanceMonitoring(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, FirebasePerformanceMonitoring, FirebasePerformanceMonitoring)
!define FirebasePerformanceMonitoring(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, FirebasePerformanceMonitoring, FirebasePerformanceMonitoring)
!define FirebasePerformanceMonitoringParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, FirebasePerformanceMonitoringParticipant, FirebasePerformanceMonitoringParticipant)
!define FirebasePerformanceMonitoringParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, FirebasePerformanceMonitoringParticipant, FirebasePerformanceMonitoringParticipant)
