sprite $FirebaseRealtimeDatabase [70x70/4z] {
xTZ74SD03CLGel-cVNOcPk3iVrDwoXAvy-Xmce3m43SI66k8HH84i8XdC168Po1Wy4aGI11uX0810m53enGClUBVDO7SO6xCDaodS6FkSj5xAJnCqL_utr60
TrA-wEfY4IQfAuOY__T8V-i-KtchlvfdE4rJCqJrIy4qrM6Z5CpxLF1HJr8mNQ_ccRxzxFhflhVtpcoY3UyaOq4-U-4
}

sprite $FirebaseRealtimeDatabaseParticipant [50x50/4z] {
pTOt5eH04CJGqlqllV4offyQgmpp4nYN2-8l-twD08m1K0OSeKe3q00q02yq00sWAzIV6kua1Qd0A1W5nmR1xO9137r2mFqYKO9h18CGVVWFHlwFQE7dO6kU
1zCJAvmbz-y6YIMn976aiPzBqZcN69EoulKV
}


!define FirebaseRealtimeDatabase(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, FirebaseRealtimeDatabase, resource)
!define FirebaseRealtimeDatabase(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, FirebaseRealtimeDatabase, resource)
!define FirebaseRealtimeDatabase_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, FirebaseRealtimeDatabase, new_resource)
!define FirebaseRealtimeDatabase_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, FirebaseRealtimeDatabase, new_resource)
!define FirebaseRealtimeDatabase_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, FirebaseRealtimeDatabase, modified_resource)
!define FirebaseRealtimeDatabase_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, FirebaseRealtimeDatabase, modified_resource)
!define FirebaseRealtimeDatabase_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, FirebaseRealtimeDatabase, deleted_resource)
!define FirebaseRealtimeDatabase_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, FirebaseRealtimeDatabase, deleted_resource)
!define FirebaseRealtimeDatabaseParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, FirebaseRealtimeDatabaseParticipant, FirebaseRealtimeDatabaseParticipant)
!define FirebaseRealtimeDatabaseParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, FirebaseRealtimeDatabaseParticipant, FirebaseRealtimeDatabaseParticipant)
