sprite $FirebaseHosting [70x70/4z] {
pTT73iD034DHylwNpZg567v50vXhuxchw7RycGM2GtOED-QGYn1axhWDCxXZ5e1GnZm08OndkQ5ucW9XZAyhTQdedjrG0VKF819GWd4wjaES6O3OcI6A3PI8
PAP0YkV8b7mni6QiAHee_aj1RrK_4QyeXt-ZLC8pfafWkEAWzEye54oeA3ORSSNh2leRyor9K0clIRc-a8i9I532e-7LEpyRtagwPdtkZJPgiVC-JMS6e0Je
VCnfvBe_s6bRcJFFcU3NTv8vSsjNuun25WpcNDhjkQCcsE2EI9B1qmil
}

sprite $FirebaseHostingParticipant [50x50/4z] {
jTP75WCX40DHrVqlxPsJ7bsJqDRy8JUEniDFeg6ZxSyOrb7GyVPky1Jm5F3S4HnD0O-SZAMG2VgdveqIi203W2OZ271S3AEGJIsoHJ29PJcP1AT5ZSn54nSV
OZF__7X6_98Qb8h4HCyaUXHJf44mqg99uCorPIolvsl9MA-amkqge_jVW-GiYH01Jkw-vqxk_Izn4uqqVm4
}


!define FirebaseHosting(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, FirebaseHosting, resource)
!define FirebaseHosting(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, FirebaseHosting, resource)
!define FirebaseHosting_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, FirebaseHosting, new_resource)
!define FirebaseHosting_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, FirebaseHosting, new_resource)
!define FirebaseHosting_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, FirebaseHosting, modified_resource)
!define FirebaseHosting_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, FirebaseHosting, modified_resource)
!define FirebaseHosting_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, FirebaseHosting, deleted_resource)
!define FirebaseHosting_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, FirebaseHosting, deleted_resource)
!define FirebaseHostingParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, FirebaseHostingParticipant, FirebaseHostingParticipant)
!define FirebaseHostingParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, FirebaseHostingParticipant, FirebaseHostingParticipant)
