sprite $FirebaseMachineLearning [70x70/4z] xS6100000CEW-rCVPDNY00000E

sprite $FirebaseMachineLearningParticipant [50x50/4z] xS410G0020AW_g_kHYamxm00i


!define FirebaseMachineLearning(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, FirebaseMachineLearning, resource)
!define FirebaseMachineLearning(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, FirebaseMachineLearning, resource)
!define FirebaseMachineLearning_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, FirebaseMachineLearning, new_resource)
!define FirebaseMachineLearning_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, FirebaseMachineLearning, new_resource)
!define FirebaseMachineLearning_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, FirebaseMachineLearning, modified_resource)
!define FirebaseMachineLearning_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, FirebaseMachineLearning, modified_resource)
!define FirebaseMachineLearning_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, FirebaseMachineLearning, deleted_resource)
!define FirebaseMachineLearning_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, FirebaseMachineLearning, deleted_resource)
!define FirebaseMachineLearningParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, FirebaseMachineLearningParticipant, FirebaseMachineLearningParticipant)
!define FirebaseMachineLearningParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, FirebaseMachineLearningParticipant, FirebaseMachineLearningParticipant)
