sprite $APIAnalytics [70x70/4z] {
xPW7JWKn34JdpVtlJ5qbikGKO523-NMj-2KkMtMfV-6JT9Pl586OOpY1nVXM4OY9K1o1c4rg0ukn0nWY57zL4OY9K1o1c2QrWSNO0GmHYh-h2CH4A8v0p4Lg
BoRQZO0oqsDZZTdYgNyaRYcbZPuHkrBqncT21cRyxpsGQ23bBoh6pgLT2lFxW_10odSHtV9cJYLDiaQAhdfnffr1iT50ypiKjXHDocEafVHvyN3GH9VrLIqh
pI1Mc_k6MNSYqw7-QrpeCDXCdCqqTWujUgWntk-ETECv707y8w40PXVglGYT0mAB2PqR4nWbA2Y1KU8oYD1rNM0neUlT14O92afWbBYr8NIl5bXCw1usWL7Y
jXm5C8c77kWFw1K
}

sprite $APIAnalyticsParticipant [50x50/4z] {
pTHLOiDG50FHqUn_p-Kczgr9PNqzq4dC_F-uaxH0hO5-Zz2I-Et26fXQE47v9z7oJxGagOKMf09cL-Gbkt-okx57yh5wss2pCER9EtcTpigSHJMWt3OX--Aj
5ZG63SpIaWU5MuVtQN1aNsH3KFy7ypnkm10bolx5ugswlaYGqTb_qk3y5WOWwwaJO97G4bwJ5a0lg06ze0R4-iFR_WMa1T0B2b28Xj2Aq19sagB_eta4
}


!define APIAnalytics(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, APIAnalytics, resource)
!define APIAnalytics(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, APIAnalytics, resource)
!define APIAnalyticsParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, APIAnalyticsParticipant, APIAnalyticsParticipant)
!define APIAnalyticsParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, APIAnalyticsParticipant, APIAnalyticsParticipant)
