sprite $APIAnalytics [70x70/16z] {
xTO5TiH030DG9qCgnVS_RI5wNdJVaihLClY7XlpC_0UdSuuXOA1W0043ZQ9We54K31GAe62WOA1H50mqYe811CoGA820mHSha20O4WLd81OvnUHAQtpPHNhh
kP8ZXQKJW178CARbJ7uOpA2uXTE3MwWS8HK0EXcp6QXy3qpSnVqao6Isum7D04JjwXsVdME5XyvDh-0Cn55DGPzAC-F1s0pkLyXnKivH9fk0E8qrb92jS3TF
X2SpbBQZL5xzyvJPRAkK7OLVLYgdpcvdHLpbQRk3C-LXXfDAL0vi2sAVEdy_gR2YOCqWk5ywPKZUxAolHXJmGndidJLJbfHXiixL4YJR6Gmw7Tl4bIxlZdQu
BQvG5bSmhb14yv62SOsYO5oX35SmojMXNd418bDSWhW4STSeTmh4NQCi2iHTWhXh51SWvp7-1_82
}

GCPEntityColoring(APIAnalytics)
!define APIAnalytics(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, APIAnalytics, APIAnalytics)
!define APIAnalytics(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, APIAnalytics, APIAnalytics)
