sprite $ApigeeAPIPlatform [70x70/16z] {
xTS7RiGm34HHgbYQLD__j6cKJMCWQuc0gCbFbRFxubvsP__XSHuZW4440sy1I9Y202HCGGY240I8KH20X2a8GC8KX23CT50zYqZkDXOHgGyKK4cq14r61TGA
4Kjdv2pxbJHUddyOHTh0smr3YBwhszg0MjzL4U4NtodPPhoBXj7fMukrSXrSXzjaG_aK6kQvWfKYscfUOCZDUf4Z6tTmxwRmDZgHL8mfvbrJX4k3ENVMmLJR
NuW1P-zIn2OKc-1BHZI142UJQ9nX-Pb22jpndg_HcDgNY5mdP6BysqXiGj49FiKG-zaLqJcQ8NVxhd5Qfh-myZwRbSRdszLnv3kc3K6Rx7XFplDBjY4fphDK
4Q7XDZal4CFdw2fQvtzWhIv7zPoJ36DilWWXnXPZmtQiMFckwMJuBsjPZWhjDusHXO8cMYFMTxctUYsrNyUbR5WXhFZhUmGJStSOeqGmUumImSG-at0nojFl
42v6UOz0_3CJzMo_BW3nCViVw1C
}

GCPEntityColoring(ApigeeAPIPlatform)
!define ApigeeAPIPlatform(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, ApigeeAPIPlatform, ApigeeAPIPlatform)
!define ApigeeAPIPlatform(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, ApigeeAPIPlatform, ApigeeAPIPlatform)
