sprite $ApigeeSense [70x70/4z] {
xPVNMaH13883x__EziAM8Un-t6dk7F4FJFLCMFy5RXL0c5G5Ggnn2cQOLWL2L2YiG0WpjGKpP0632eMFLWL2L2WC8Ska8PlQi8iNOGsSMCaKlbCKEeHeFHxw
iZ-CReFWHctCu03vKSdOsOo3Q9P3HvldgjStCAP0cqeiP-QGytPK5kwcA-mIgm-SEd36n9Hy7yF7RGDFKSSpPZqCHOUUe-YV4Xi56mM95pClNwZ1hFCoC1HT
Mxz6SzmllziU9Fn-kJAZ_KIFCO7SdQ47H7_E3xNU1ScPzcO8kSXWj8OFFwJZwGLcRBlhMnl0wqHhVfsgp2jjDMo_zbxasnXCJ8ccZaYizF-l6pm3APYP1cOQ
54m3CurF6vI-rGfcnbM7CWL8d0bJm5X0oC7yWNe5
}

sprite $ApigeeSenseParticipant [50x50/4z] {
pPK5jiD030Cbt__E7qD-ohJFPRKXUMSPzFaga15W8S2Q4m3Ca7euKMEWF2OgW5aXFi-E2k6G2U484k5JNWWiLWPzHZGZemmipwYOpfoM6UG8tvApb0HqY4Yx
nqIhdXn4-LAbIjfDd9rBIYQ4XEK1KHAsG-h4ZXZwglDkeoPvSHgHnZxX75d2x5mUhWHyPUuQvgwSfdXcfrlc3G03w2FXtHvkFm14uqc-Sz-Lfu0q9pG4viJZ
JsThYWXaIlzgVGC
}


!define ApigeeSense(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, ApigeeSense, resource)
!define ApigeeSense(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, ApigeeSense, resource)
!define ApigeeSenseParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, ApigeeSenseParticipant, ApigeeSenseParticipant)
!define ApigeeSenseParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, ApigeeSenseParticipant, ApigeeSenseParticipant)
