sprite $APIMonetization [70x70/4z] {
xPOtWiLG2CGaxd_dpQ72yEpfTlLJfpyCJYpvnvfWfZP49EKuJY1CROb8oeYb8f8-Z7L27oMWCMAfKoAICcAfYAIyLQrJc6N-QuqHI-qjlMRTvMN1TP-znD_V
Feppt_dTInzc4xgtr229M-nsL8t-7C75SkRwXr667NqYGwiCxSwuj-mdihTO2TWinz5YKyZ9HBOdc0Vj0hOhPca186FXeOM4HRvuPE4R7rZaXmURvXTl7tMG
k26Hq92mI48pF67kCFHS5mWJUjvDQ4XO9A6XmqGKI4G14nB8M8X8S5bjGCF8x94_m2i
}

sprite $APIMonetizationParticipant [50x50/4z] {
pTG50i8m04FHdzp_phYt6GGFplRgBVyVXoY2d0HAqWkx97wxS0siMdW0NIMooqgS0feIPG5JuGU54yZHef0ERsCbImq2Hg9QE4GStcw9YqGXa7ruOxWQLaFe
HmgStpHST1jIyRcEQmBSwGVG2of1AyGkXM0VtGY1vW8OAz7r8Xogw7OXlMW9xH6d5yzTr0Be1GKeH4DeXMW98V8yV3jh
}


!define APIMonetization(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, APIMonetization, resource)
!define APIMonetization(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, APIMonetization, resource)
!define APIMonetizationParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, APIMonetizationParticipant, APIMonetizationParticipant)
!define APIMonetizationParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, APIMonetizationParticipant, APIMonetizationParticipant)
