sprite $CloudEndpoints [70x70/4z] {
xTOvSiD050FH1kv_QCUggK_FDpkpEjFs2jf8SjctzBSkaDwa8Ct-xUp7z3O5QHIb2ZAFIIkCQGKcYj9j2j8eIXNa79DM6DCAJ1IbVqr16aNfWRmRarOOqtVD
I4ZFOAK4E1aOc1cXHynFpu2azmmia9498x9XdX0-sp0VBnYOOsckcJnieG_CzMDamSpV4RrdnllddrTUuvs6i_jJ3__q6Q6l2WQ3SSYCT0uGnaZdHeF1K8B1
O5m6HRgk4yP8rxi6Ww44Ws4gnXGmfa0C11m51I6zAGWCGnid_8D-
}

sprite $CloudEndpointsParticipant [50x50/4z] {
pTJ7WKGX40DHgV8FUi_Rz9WQhzCtF3pazmDxQW6W0NYX0MY05sX0jM02sKX1DWAIL0iGH06g1Hh0CkpntXpY_7BrdGLqViWcTh2JJd0ixQqhO-ouPIXPUj01
5Z687FhD3xVNepUNaFzPG13fWtitjI3n8Xh4YmWW1jydxztKWiIB22248R6YiIJPK_Raq_a3
}


!define CloudEndpoints(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudEndpoints, resource)
!define CloudEndpoints(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudEndpoints, resource)
!define CloudEndpoints_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudEndpoints, new_resource)
!define CloudEndpoints_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudEndpoints, new_resource)
!define CloudEndpoints_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudEndpoints, modified_resource)
!define CloudEndpoints_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudEndpoints, modified_resource)
!define CloudEndpoints_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudEndpoints, deleted_resource)
!define CloudEndpoints_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudEndpoints, deleted_resource)
!define CloudEndpointsParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudEndpointsParticipant, CloudEndpointsParticipant)
!define CloudEndpointsParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudEndpointsParticipant, CloudEndpointsParticipant)
