sprite $DeveloperPortal [70x70/4z] {
xPSv0iGm20CP_l_ehMDbiHnezb0N7nE1xp3r5xcJ0Kb78v342ATj9bsDG98HIfQGlXdoH8MLFeOHIfvg19ACK784ecQes-6PsV-AFGOdTrjAKG_Llnm8yhsA
aeBqAMAgKbkMg1co8x7ImKYf6hx6u50k1NT1nnr6YnIo5289HhaB19awsaaX8KXbivYnDWnEjjTGlQsXIz6XnOkeXkJ3x2xTzYDDBdbG24zctLqVZ1Mmb2da
V3LAXwcTeKyXAeovOsOvcztTcvEJXAAXSLnHR_F5sUYViEcqy4zxfVX75eLTNyNUvOkfUrtVpDXzju-92GenWOc9fmrJRxM-cVathAeFyMCY1Z1X2CF8r-i5
}

sprite $DeveloperPortalParticipant [50x50/4z] {
pPK73iCm54A1-z-vUs7nrTADXWTvSOWN_byQn08ugmQazn1IYUZjX6f0h0dLW0z2gHnai3WY7FfdnxelJp9u2U1jHp132lAcaHEgqHgE-TkSi2OzuQLbY3Le
071fPW9dWiVAbJ24UQ7b7XSV9M08ZphwFBSD46oKsqJCoGL3yc9O06Zy3N6fzAka9GX3GhBLJ1kD5ZdlgFYURDtlvsGW9cHp_6IXFUBOdxikjW3G4oY1ddZ_
xKoq20PHMVYsjW
}


GCPEntityColoring(DeveloperPortal)
!define DeveloperPortal(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, DeveloperPortal, DeveloperPortal)
!define DeveloperPortal(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, DeveloperPortal, DeveloperPortal)
!define DeveloperPortalParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, DeveloperPortalParticipant, DeveloperPortalParticipant)
!define DeveloperPortalParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, DeveloperPortalParticipant, DeveloperPortalParticipant)
