sprite $CloudBigtable [70x70/4z] {
xTS5TiH038DX_Rx_dOjQZbodpmzR5nRpZJnX3Uk_g9zgWDIaLf3YV3ldmzIqLf1YHQaL98UXpbIEii2mejJP6YFGA8oZj8sE-sbRPJorxOV3A7X0HWmniR-g
YT9qtJizui-lxLm3Aqzm2CBrYHy_jHWc6jot8oiX38VDl3xwBuHf3G-O5JEf6J_wuPpY7T16tU96fMv8RihLA4W4v6LdYqfuas-ZD5M8okSVkQE-h7p_tHpg
ruf4bUI7Jg5Hoe3NGgEeKxpl8ByWAcJ5WgUsh8PXa-8CRYOTh6oJ57zyVI0OnfE20GTv85yK1ULXQfiZi7e53ziQXLn1yKmyxftvBC2Byj18UtOZ7RvvdWZQ
jHp2mCkXCnark7XvE5enFiNc8oSrGAma9nKQChHZpAymyuUSkiJCqnR3p6lfUdU3qOQ2DXYbOY7ArhsQs42a7KKBoBWdjC0erjn1Vw3U0G
}

GCPEntityColoring(CloudBigtable)
!define CloudBigtable(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudBigtable, CloudBigtable)
!define CloudBigtable(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudBigtable, CloudBigtable)
