sprite $CloudDatastore [70x70/4z] {
vTY53GD100D1U_ilEg8JFCE6BGgE_XWYvVTJzfBzS2GAGdUB8pmCHwCWL55GaFM7AGWF0m9JHU5i58Gg2WeoVvY2y30WC5KKhaP1gAAW87GW1U5XG63Ml-bu
mNZHgmeGnekk_PZRIfFULqZOKzg6yM9PwQR2_CNdfnW9tErrEsrtM6aYA4bwMp56u_ZgPgzJvfV6O69CcPNM0E5XfBNHO68eZS74s0PLsjS93oFjTmqcXj8O
J8oZJQMpcl0mqXdMO68Sonk1CIuzcZ_80m
}

GCPEntityColoring(CloudDatastore)
!define CloudDatastore(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudDatastore, CloudDatastore)
!define CloudDatastore(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudDatastore, CloudDatastore)
