sprite $CloudDatastore [70x70/16z] {
xTRLOSGm00HHioQaxR_QC9DfWdTh1hqVOHRc6EQpn10O30O41aSn61p5O30KC1WC1aSn61p5O41WYgA0mF332Wf2KHGK13pbVQIvpVHmmyDD-OXXHW5kZnPu
NwcAGeAWCAyCmz3mS5DOa-vM0TfNDuUIm8vMDwi0twmaSPJwlj9rtLBbmpxTFnJkvbjT-JsZL8t1n50IWud1n54C9ePIOZ3cwj1N8Y2Q4WM9WYIESc8WYQDK
0qaK976K2CWo9WUGAm
}

GCPEntityColoring(CloudDatastore)
!define CloudDatastore(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudDatastore, CloudDatastore)
!define CloudDatastore(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudDatastore, CloudDatastore)
