sprite $CloudMemorystore [70x70/4z] {
xTOtGWKn00FH6Tt_qBGa8_z57QZSy9m3b_cFQQ4dDvaWiJPdK9dSPeB4YP89SgwCoQ0ooO1nekJLJ90uKLAGfvKn6LGc6J1EbCS3K5vVAawKdD-gyarKFPNc
I_lXwUCK9G2KhzkyF1GtLWAGegGgWXTJgK-zCgzpepXHpl7ZBxu4d7xZHyL3Yuvj-lw7AyMs9ErAtqKMiow0LQ4e03J5hlIT8Mt3eoZVvbZfoLw7lzYz7Py1
E3dLoDEmO5Weic1ON8CStUi6bHdTTnSC2qKM3AUug0eigW8k4DWeJ13CJMJ0KDCT-GDv0m
}

sprite $CloudMemorystoreParticipant [50x50/4z] {
pTMfbGGm40DHgV8FUj6oBg2vHUt_shVp-q5I1PuPm6i4Z8IN2sP0Py41bYA5iGYCfBF09zYp3N1nJbwxMxiKw2NuhtiW6cjb4kYquHoL2rHG06HkjhaoDnCw
3zzX5n4Xgukkhekeo3qgkJrHaLjqFUt8hN6nNdF8IhABbSW4FNtotKrNaEmY8zZ5wt_dPYMHrFf_Edy
}


!define CloudMemorystore(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudMemorystore, resource)
!define CloudMemorystore(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudMemorystore, resource)
!define CloudMemorystore_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudMemorystore, new_resource)
!define CloudMemorystore_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudMemorystore, new_resource)
!define CloudMemorystore_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudMemorystore, modified_resource)
!define CloudMemorystore_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudMemorystore, modified_resource)
!define CloudMemorystore_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudMemorystore, deleted_resource)
!define CloudMemorystore_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudMemorystore, deleted_resource)
!define CloudMemorystoreParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudMemorystoreParticipant, CloudMemorystoreParticipant)
!define CloudMemorystoreParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudMemorystoreParticipant, CloudMemorystoreParticipant)
