sprite $CloudSpanner [70x70/4z] {
xTO7KWD144FHBzt_pcHmx5KRL17BsJlrIfk7PPwHKyZn9XN4YgjJAEDjAeXLKLn1vZAo2sNi0gEAuaTJGQoAuWfYXKsxpBAAm3Ri6Cs3JXzHSLOouryhMYiA
Gm9YJd4geuqInsmEApamFaembeeZOWTagGZqTyNWWgAAaZFiW5sa7-FKPjHqj1xYC-5q6lY7PnKe8egC82Yw_kD-TzrLp6SkO0dOxaQXcmFbL6jxEieU5Ky8
c_ETaH4Z0_SK3lUe1b-BteBZChw8ve5pqSrVuL3QXmP3Gn4DXiOqIALvNQ5CQRxRO6Weei4mHOqgqAW2QY3GKQWWo9k80aDCTiG_o2i
}

sprite $CloudSpannerParticipant [50x50/4z] {
pTG5iWGX54FHc-n_pr_7UPdgZAUiXOC3dn-7A8AS6jYF4NP9_73X6bYry0AwHkGjkTg4R2aJjBPlQ_sUco089v25aiWJ4e0LXNUVonyUG_xXfmkh4haEmOwi
ZccIs6UQ6keh0sPXUnRBkqw_0METUPgcdwlGoQVm5vOw57Vgj4K5MoPcQsW9lMW9xHMdE-zTr0Be1GKeH4DeXMW98V8SNfrl
}


!define CloudSpanner(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSpanner, resource)
!define CloudSpanner(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSpanner, resource)
!define CloudSpanner_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSpanner, new_resource)
!define CloudSpanner_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSpanner, new_resource)
!define CloudSpanner_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSpanner, modified_resource)
!define CloudSpanner_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSpanner, modified_resource)
!define CloudSpanner_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSpanner, deleted_resource)
!define CloudSpanner_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSpanner, deleted_resource)
!define CloudSpannerParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudSpannerParticipant, CloudSpannerParticipant)
!define CloudSpannerParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudSpannerParticipant, CloudSpannerParticipant)
