sprite $CloudSQL [70x70/4z] {
xPS7RWD130Cv-l-Vqzkwa4f0r9WeAIkCYbVqdPPwY4bIrcnKWGondK8nirK5CbGeKu4CPhI5OcOA62gK-QqgaA52cGfas8yMiIx6frjYI54hIeuXXwncHmgo
nxuj2pdEs6JZFkM8DSMOimD_VtvoHoU6JCbrnWkHLYJVFIIsEs93zullTliUWHiNym-cUd1S-wcRpryuVhaX3EM3ym5pb6GSV8mlK1R-X0A4jHlAHt9tNbmn
c5DvKKyE7_-x9UyC79yDz-gEHlZnsrTLkBrTEmCcKWGxpIwVpTrVb-WSEcLYaearlcBp0YqeoH06RJ7ZZh8rPr5whYiKKthURM3KeA06HerN6qhlQeLYvDIX
g01PzuGA64Lb3le7UWO
}

sprite $CloudSQLParticipant [50x50/4z] {
pPK73iDG34BXtV_GrSp4RUaCsbWltqkEhYy6kGM06e3F450YV9oW1d1D483c4KFvI8pUGvn3deanOGz8j4an9yBBnnEIFxDQGmAk2IYo0caQhHEGYTpTLJuP
0jOcFhdKovR4j69ANfiVYJoaedINIssl2-UGGzmImvhP2GZ4sjPnUGTltbqvkX5OxIAG8uuk3zhkwlnagJrnVlFkoYqWzOHAe2S-_tUsMaI3J9P-hHi
}


!define CloudSQL(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSQL, resource)
!define CloudSQL(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSQL, resource)
!define CloudSQL_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSQL, new_resource)
!define CloudSQL_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSQL, new_resource)
!define CloudSQL_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSQL, modified_resource)
!define CloudSQL_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSQL, modified_resource)
!define CloudSQL_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSQL, deleted_resource)
!define CloudSQL_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSQL, deleted_resource)
!define CloudSQLParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudSQLParticipant, CloudSQLParticipant)
!define CloudSQLParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudSQLParticipant, CloudSQLParticipant)
