sprite $CloudBigtable [70x70/4z] {
xTS5TiH038DX_Rx_dOjQZbodpmzR5nRpZJnX3Uk_g9zgWDIaLf3YV3ldmzIqLf1YHQaL98UXpbIEii2mejJP6YFGA8oZj8sE-sbRPJorxOV3A7X0HWmniR-g
YT9qtJizui-lxLm3Aqzm2CBrYHy_jHWc6jot8oiX38VDl3xwBuHf3G-O5JEf6J_wuPpY7T16tU96fMv8RihLA4W4v6LdYqfuas-ZD5M8okSVkQE-h7p_tHpg
ruf4bUI7Jg5Hoe3NGgEeKxpl8ByWAcJ5WgUsh8PXa-8CRYOTh6oJ57zyVI0OnfE20GTv85yK1ULXQfiZi7e53ziQXLn1yKmyxftvBC2Byj18UtOZ7RvvdWZQ
jHp2mCkXCnark7XvE5enFiNc8oSrGAma9nKQChHZpAymyuUSkiJCqnR3p6lfUdU3qOQ2DXYbOY7ArhsQs42a7KKBoBWdjC0erjn1Vw3U0G
}

sprite $CloudBigtableParticipant [50x50/4z] {
pTK7ZiKW54DH--v_prF3amWM-W6cM3Nb19o6_dyWnqy1y1Z06G4F2SS5Zm5-B9W3cVaW3jUR3vAFJeZJ26b_9StNDJMF95MGz6r1L1p4TNMtiqLtV02k1jSm
laH7F9wlLZuBAhsIp2YG8DHeUKa0dWby4o2WWIG8OjOS54GzHBygPAuME5MDOu0Wle-A0akeNXMx5yhDw-NjJr4KRirBLQoUt6RliSRu2TOib6ktnDz2F58X
ly04a0LexVSp0p9ZxiAR_rtvAP2U2pq4pyNvrTbwIgGSawFVpZi
}


!define CloudBigtable(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudBigtable, resource)
!define CloudBigtable(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudBigtable, resource)
!define CloudBigtable_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudBigtable, new_resource)
!define CloudBigtable_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudBigtable, new_resource)
!define CloudBigtable_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudBigtable, modified_resource)
!define CloudBigtable_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudBigtable, modified_resource)
!define CloudBigtable_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudBigtable, deleted_resource)
!define CloudBigtable_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudBigtable, deleted_resource)
!define CloudBigtableParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudBigtableParticipant, CloudBigtableParticipant)
!define CloudBigtableParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudBigtableParticipant, CloudBigtableParticipant)
