sprite $CloudSpanner [70x70/4z] {
xTO7KWD144FHBzt_pcHmx5KRL17BsJlrIfk7PPwHKyZn9XN4YgjJAEDjAeXLKLn1vZAo2sNi0gEAuaTJGQoAuWfYXKsxpBAAm3Ri6Cs3JXzHSLOouryhMYiA
Gm9YJd4geuqInsmEApamFaembeeZOWTagGZqTyNWWgAAaZFiW5sa7-FKPjHqj1xYC-5q6lY7PnKe8egC82Yw_kD-TzrLp6SkO0dOxaQXcmFbL6jxEieU5Ky8
c_ETaH4Z0_SK3lUe1b-BteBZChw8ve5pqSrVuL3QXmP3Gn4DXiOqIALvNQ5CQRxRO6Weei4mHOqgqAW2QY3GKQWWo9k80aDCTiG_o2i
}

GCPEntityColoring(CloudSpanner)
!define CloudSpanner(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSpanner, CloudSpanner)
!define CloudSpanner(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSpanner, CloudSpanner)
