sprite $CloudDatastore [70x70/4z] {
vTY53GD100D1U_ilEg8JFCE6BGgE_XWYvVTJzfBzS2GAGdUB8pmCHwCWL55GaFM7AGWF0m9JHU5i58Gg2WeoVvY2y30WC5KKhaP1gAAW87GW1U5XG63Ml-bu
mNZHgmeGnekk_PZRIfFULqZOKzg6yM9PwQR2_CNdfnW9tErrEsrtM6aYA4bwMp56u_ZgPgzJvfV6O69CcPNM0E5XfBNHO68eZS74s0PLsjS93oFjTmqcXj8O
J8oZJQMpcl0mqXdMO68Sonk1CIuzcZ_80m
}

sprite $CloudDatastoreParticipant [50x50/4z] {
pTI5aSH050DHgVFF-MZgYhwfbsM6PnZAvuUTr0900_120z00Bz20Qi40xYK5-HAGf5g080fGBT1WaSvJQnsw3kPbc08Q6fZNmGlrLT1nektQ_1_SdPslQfAk
WtFH7l_7E1Cu5Bb5PBTqzou7aSQIhDI2n8je42yYWFZvtZdkfXOaNaG08Go95OqbsKd5_K_DDm
}


!define CloudDatastore(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudDatastore, resource)
!define CloudDatastore(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudDatastore, resource)
!define CloudDatastore_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudDatastore, new_resource)
!define CloudDatastore_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudDatastore, new_resource)
!define CloudDatastore_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudDatastore, modified_resource)
!define CloudDatastore_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudDatastore, modified_resource)
!define CloudDatastore_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudDatastore, deleted_resource)
!define CloudDatastore_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudDatastore, deleted_resource)
!define CloudDatastoreParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudDatastoreParticipant, CloudDatastoreParticipant)
!define CloudDatastoreParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudDatastoreParticipant, CloudDatastoreParticipant)
