sprite $CloudFirestore [70x70/4z] {
jTS7RWGn34DHVTx_pkbbfqYc0GvHqfm7hRlh6XOf8sWL30GjmzAHavM24emI2aemIYWemIYXe023Cag0GPl9A9Z8VZ7Q3qOfMGLiXh4XPiymRsg0KOpH1aCP
MjYDy3Pe61diJPvUOUuGnibfAKXYKkWGSUu9Q1KnAiVUX5d1dB0qYdhblmxu__PUuHxHyHyFfEuPhAMFvcRk1GD6nT-2C1JpcF3x1RQEJuprVYIxmaS5Jkh6
fihb0p0fyzBWHjvSZN3Rl2-STQT3Dp6eLg6hZLufZS4y131FOxoZP5-fNGLMwssjO2nQ5WfeK0o6rf1ojw3ylQw8AFkCuhVc_qIG8g8KUqX2oRmR8yhpxsdy
KW8C4QKgm501Xbg7Djy4r4Dv1m
}

sprite $CloudFirestoreParticipant [50x50/4z] {
dPP75aGX20Gjxd_esKsYQ1-_TuQcZEZv4QepYXf4CEmi5HGG6qX5EM89gOiCiOJKLOR8mX1PXiWY8o12q704oDJ2147wvwQuKT0Xc05qp2E2RtTpC2yIpL6j
0eaGEnHy6j2jz1E5B5Do4CyRvtPpRWok2M0w1rJX55cyJrZ4qQZyLj3FHAlvwLzLsBcYL5XJIWkwKh9-sK7CFRuN2IBLv0GdOVOPRfr5dsJg9UJ1YxErx5_E
_Uii8YEsbkDA21Si38iVsGi
}


!define CloudFirestore(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudFirestore, resource)
!define CloudFirestore(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudFirestore, resource)
!define CloudFirestore_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudFirestore, new_resource)
!define CloudFirestore_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudFirestore, new_resource)
!define CloudFirestore_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudFirestore, modified_resource)
!define CloudFirestore_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudFirestore, modified_resource)
!define CloudFirestore_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudFirestore, deleted_resource)
!define CloudFirestore_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudFirestore, deleted_resource)
!define CloudFirestoreParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudFirestoreParticipant, CloudFirestoreParticipant)
!define CloudFirestoreParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudFirestoreParticipant, CloudFirestoreParticipant)
