sprite $AdvancedSolutionsLab [70x70/4z] {
xPO7Rk0m30Hdzlz_lcfUCKXP1XIqPDDP1klGAcpgI-P9F2ixEWA9Zuzpm4nsTGGIZr1o13ARCJbW9k_qoehwXZ90Plu-98kSsvHbSXCY9RVCE1G9rtStp0mb
0H42y8YnPyIBOWMMb6c-434mpNo4g5KlNXIBhKx_u3kz8l2Rb0fqvQKxl0BWHH7kwRkPnc9HSb42qwlSM2bCTLwKCjCEj9yF812XA3MjQjYZS3alIeNDsD05
JG1Jb2e5svVBXXAuZ1P5YXBeEhgOMFPB_YQrBVQKUjJYr1z5UL1HX6QNWdmanUKJkVb4j1ImM9H-8sqfpvEkxuj92zCkTtjthMdt7NOK-nL0EWfZ47DV0GOM
3KtiQloFico037kTMD_BM6mR-XtJztlTl6NQxzxJ8J2DxaRf9xe-6dCxrV9uE2Qz7L0KAh1nn3PsG0gI9mZfImINTvCDZ0_vRDumrn3thvXpBllNtGNbr7rt
7nFp1a9UIKvWcEG9At322dW20cSe787W5aGEO1Yrpv5FeEy
}

sprite $AdvancedSolutionsLabParticipant [50x50/4z] {
pPK7SiD030CN-F-Vqmvf1zqmFOOxfMM1EHAtBn-a4MYDGEi7Y0Pcn3zEU0HKWO6WGmLKGXsBz45TXyybG0k04wAQ06DgciiIAoyOvviQuLrWOVPw9hWFM9OY
6rkKqG7s6kijfFeKxQuQXn3U7UknIHF1eFtoEoAMBa8nUY004oa_poigacCnIRaH_ZJHNMK0o3TDH1QTZ2En4PztjmZGAz7_e8SjuN9Bw8elHFKXtYERfL1j
iAGQB4GDIjJkWN6-k8b6PDQZWIAMndWVcW7a-IggRrvtkuW60FpZjnn-WFZfkxFuBC916ix_Czq3
}


!define AdvancedSolutionsLab(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AdvancedSolutionsLab, resource)
!define AdvancedSolutionsLab(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AdvancedSolutionsLab, resource)
!define AdvancedSolutionsLabParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, AdvancedSolutionsLabParticipant, AdvancedSolutionsLabParticipant)
!define AdvancedSolutionsLabParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, AdvancedSolutionsLabParticipant, AdvancedSolutionsLabParticipant)
