sprite $AdvancedSolutionsLab [70x70/16z] {
xTO7TXmX48JX7sReBkVxdzQndXAzNlQnpYx5IPyQ3Ud3Olv7rxDhEFTHj83iChgNii_efokw2w9TnBb9oJDLvmOaWB6j0A0woqW7uDXI1ZXrerQG10RuUrvd
KdE0BaW6g0DN5Kqv02dfIK0QdV9T9Dm4K182kO7BoZaUxZyvlogDUB37c9aP0Hvg1trL16xdr7soL1B0lpVIok2OBZiLednUYXN1nQvSAJe1y9CFIj8UUlAe
bAAV3411i-Aw0ZYAVbCXeeCwWAmOXnI5yhvKZkPUDfue7RhKo5bHWOX3804WA-4Z46XAhPn48zMXTQ03eU0mDATK7fgFqtnmcnBW0y2YWP-kk149ZaLqmt_t
8402EW0DkeAZ4qlA_ARz_VOt3TBveky641eSXLAF05fGZW04jV9-KW08TVA9qWarQ40vQrR8gHSpWm-0YNbrQPRociPuKBhR5Ikpb9NpubpN9-LzlGG0OB5R
QTW5kB08L6lyADQ0mrNEICq8C9E44U36nT5_5pA9f4-5J8YLiXn80dnKA5UP3YSC3heBcP7hYX8UeYgvjYFhmFwMpELe4R4ofoqeQyN4Ec9bJjnb2x-AEBk8
Sn_brIRYt4TvluaukuYpgpYxYBDW_0Fv1
}

GCPEntityColoring(AdvancedSolutionsLab)
!define AdvancedSolutionsLab(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AdvancedSolutionsLab, AdvancedSolutionsLab)
!define AdvancedSolutionsLab(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AdvancedSolutionsLab, AdvancedSolutionsLab)
