sprite $AIHub [70x70/4z] {
xPS5hWGn34FxVFyxVqPFKsUq4Q-5fHSehvwU0WL1XgWXCcG0ewQIAmFEgAq9LoGc81BJ58SCO7HJbIi3pkYsRhZ2eQaB8RPc2bXpe10xqS1qJ94Ip8w0S-1i
QD_AbNDoXie2CIoinHgS4tk7Z1cdwCuvL33oFYOv1LauI9GKxVF-FOWYpTlvr8uYBNmnK51ahXZ5bZVruaAFKyIH0asAZXI92mLbZ5Ea_nIaXodiSy3gKuJ4
FY_dcVv7AHSOQTKXsmt5gbkK57rmUZjWbHIatua9kt5HvuNT0LoSTZZxcz8-fQxrtqdbEy7nnAoFP6m7b5t3JUAhxih8hImPfUYMRbYd49ymr4-Nq2DXREss
NbC3hw215zd0wt3ufNhVcQ4N_0Hcu9Crz45YvCStzViSS6ReLpw0OIL14vBrr2i
}

sprite $AIHubParticipant [50x50/4z] {
pPK7YWGn30HL_Vz77yc3GOK6NUxDMXUAoFNlHU9Y05O86SIUS629v4NcOkaahzgwI9W1p3OG8COm08FTqYPKEQDcgkfcm9nq6pVJdI217aGFe2c35e0M4vS3
GYFIqZwlSz8gaqxKeqwaC8A184Q4GqY3KIBX8SYAWD0Y5uA722rpgovLd8xet3LYw22bn3GbRT0u_M2On3PPgVZa9cQZJdNrJrzMDq5k3Pk1e7P1j8X7-mst
twBxJRs_3PPEQd-hRP4opIvCJ82B5U02e7vV7m
}


!define AIHub(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AIHub, resource)
!define AIHub(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AIHub, resource)
!define AIHubParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, AIHubParticipant, AIHubParticipant)
!define AIHubParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, AIHubParticipant, AIHubParticipant)
