sprite $AIHub [70x70/4z] {
xPS5hWGn34FxVFyxVqPFKsUq4Q-5fHSehvwU0WL1XgWXCcG0ewQIAmFEgAq9LoGc81BJ58SCO7HJbIi3pkYsRhZ2eQaB8RPc2bXpe10xqS1qJ94Ip8w0S-1i
QD_AbNDoXie2CIoinHgS4tk7Z1cdwCuvL33oFYOv1LauI9GKxVF-FOWYpTlvr8uYBNmnK51ahXZ5bZVruaAFKyIH0asAZXI92mLbZ5Ea_nIaXodiSy3gKuJ4
FY_dcVv7AHSOQTKXsmt5gbkK57rmUZjWbHIatua9kt5HvuNT0LoSTZZxcz8-fQxrtqdbEy7nnAoFP6m7b5t3JUAhxih8hImPfUYMRbYd49ymr4-Nq2DXREss
NbC3hw215zd0wt3ufNhVcQ4N_0Hcu9Crz45YvCStzViSS6ReLpw0OIL14vBrr2i
}

GCPEntityColoring(AIHub)
!define AIHub(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AIHub, AIHub)
!define AIHub(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AIHub, AIHub)
