sprite $AutoMLNaturalLanguage [70x70/4z] {
xPT7ZaKn3CD2tV_Eq_lOiGLe-RL-8AYNVdPv13G4PeWMOOO4C5h6Ll5bj8wduiiW8uGfCyJ7o8oXuih8Ja95me0u6EOlPWfDQGypozR_t-dJKx1LK964YiJy
QxK8Kn-qIK958g4YtN_jpz9CCctHBKKN5LHIA7YulvPw1bzL93voavTGuo9LZJWTffIXfdHbKOcHgaQqowwae2BzZwzR8XMDUfLcI4iAjsN7bdBV0RHAhsAj
tMbp9Q3oae1AAtEANFVvje9rX3Af37rw6KUbby5GSJ3Clf8VGZUoW4pgfXgG2TtW4vZJHKO8lR82Cg7NPm8JUfK7C9mfO4BwFF8C
}

sprite $AutoMLNaturalLanguageParticipant [50x50/4z] {
pPK70iCm20CZ_l_dxa4HvBfRTO_B6HBRozz7CKG4UCG08qmmm4X0KC6Im9W28m08YHJbJ8H6-IIvTxYay1Qg-tgzXPD2q2xPGQZ3WOgSjkpJQu-gALk5q2tO
AKhADsgho0wLqQaYEgCPdedencJT2Jj0TdYxhOM5Q2zKnHmzU1Mr2aD8SKnVnTfSa04ue-zTPN0sUzc6mF9ZxhSlYdfcfGO9A5Zoygx6oDA551uHu14374bQ
lfyj
}


!define AutoMLNaturalLanguage(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AutoMLNaturalLanguage, resource)
!define AutoMLNaturalLanguage(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AutoMLNaturalLanguage, resource)
!define AutoMLNaturalLanguage_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AutoMLNaturalLanguage, new_resource)
!define AutoMLNaturalLanguage_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AutoMLNaturalLanguage, new_resource)
!define AutoMLNaturalLanguage_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AutoMLNaturalLanguage, modified_resource)
!define AutoMLNaturalLanguage_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AutoMLNaturalLanguage, modified_resource)
!define AutoMLNaturalLanguage_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AutoMLNaturalLanguage, deleted_resource)
!define AutoMLNaturalLanguage_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AutoMLNaturalLanguage, deleted_resource)
!define AutoMLNaturalLanguageParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, AutoMLNaturalLanguageParticipant, AutoMLNaturalLanguageParticipant)
!define AutoMLNaturalLanguageParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, AutoMLNaturalLanguageParticipant, AutoMLNaturalLanguageParticipant)
