sprite $AutoMLTables [70x70/4z] {
xPS7RaCn3CLCtV_EtLMNRRu2mivhinE2-juhooDG4d181S4X0vWAOoe3CXL7LC8Wa30CKt98Zgb_HbJ282fXH2KCEyW01l-6Kv2YCupBxg-_rPDH49Mm5ITK
gl1BMq6mUgWagXA5I0LJkb_QwY_XCbQeNw6B2f_Lq2zFzI6NzksHRnJsFVYcqjNGb7rrdDh_-tEQmeem_SqDfLyRfJ6rfN0STbjAxIZdFjtW_INlLeQhobhU
lP4nwltoUojVXrr9m5H4fgCgZX6Lpmoe76LM9vpdmus5BA6OYjHpbWbLH8POnJ6k8ZLv6DgH3SXCxLG7P8Psy1COEMHbOUYKDI0pTFgSm0oToWSmB0k44CyZ
pm
}

sprite $AutoMLTablesParticipant [50x50/4z] {
pPK50W8n4CIQ_l_FsE9i69mRN7BP-bXyc18Kq921Z6GY0ncP8L6H9JF651uCy60rSHuZKBb97YtN5Dw5T5_Vxq9J4BgBcuka7fwj0X6rpQwtKXnDiza9g7Ut
javH0Wwsws5iMr62CRhok4OueaNKMo6gWYkY6R7PNA28IJUYzT4xiPceZjJp4xF858w8ecBhsTS21lXoUtIN2Qkv4ZQJiFs8-uER8g_krA-V1bdozgcMaT4b
A9eG0KSSo04OlyyQ
}


!define AutoMLTables(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AutoMLTables, resource)
!define AutoMLTables(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AutoMLTables, resource)
!define AutoMLTablesParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, AutoMLTablesParticipant, AutoMLTablesParticipant)
!define AutoMLTablesParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, AutoMLTablesParticipant, AutoMLTablesParticipant)
