sprite $AutoMLVideoIntelligence [70x70/4z] {
xPU7RaCn3CJC-_z_xbHdVBOE47ROPYS4txPNZoUW2t2Ng06vHBb6JUAKF4PjifGy1WKmOmaakKOXGKeQenYJ4a8WIJG4tx3VmInqfl6VdzT_iZpUGfo2Daoa
IDnNRRIrtIUeGvBY8Kdnd5TjT1mS5XJgximXXVAfXFfaf-IyQZzjrAq-rIESKhGMdo_uQZO7fKoBoYA0RmkhgQblxYrkuw6jHjej4VQmsreaFQnTjqzNirdb
3rlQfvJPy7klyv9ARd8-0sIN3OoTWHIZILAAWHGRiuhs9SSkGdG9fPNYbyV792a-XY0bqN3lbN8O6f4Dn4oDL0TYXaRm4vhbKC3KB6iWPcZsEQ4Pd9LxI2GU
22MU9wy
}

sprite $AutoMLVideoIntelligenceParticipant [50x50/4z] {
pPK7ba8n3CIYtF_EktJo61lHGQ_-eepJny_3RC2411TSSSC5LwQW4HuobOXG246XCrZf3DhmBkJMSYqYXv3gzVKXx2AGuI8QiH6U6h5ITbkciOfW37PVsC_e
N2aZ63k5_SUBKAg1Oi3UsR-aDVPVLoC69uhSVrohoXahYbnxdiDjMwDSgCWKsunvH8H8n9vkF_TxWH1qHzzwokXkpcut2YlMLEBbkd1xoDEtWOSyVQkvCYei
8i6411SSWF5v_W4
}


!define AutoMLVideoIntelligence(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AutoMLVideoIntelligence, resource)
!define AutoMLVideoIntelligence(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AutoMLVideoIntelligence, resource)
!define AutoMLVideoIntelligenceParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, AutoMLVideoIntelligenceParticipant, AutoMLVideoIntelligenceParticipant)
!define AutoMLVideoIntelligenceParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, AutoMLVideoIntelligenceParticipant, AutoMLVideoIntelligenceParticipant)
