sprite $AutoMLTranslation [70x70/4z] {
xPT7TWCn3CK8tl_GMRahnFSyBltJYp6WkYhBBz0IS4W7mI4Bc0vZAWio7KTKmY2GC2nJSaYEwIyZAc4GbJ2Y4WQ1NCNW_-4KfEWC4tM0DJ1NUn5H2NjnGwKR
RzeEWjL39r6LA4GgIfkRzlvFYSnGADay6rJe8uK33cbQxhc_u5GVWuhAtyD__V_yxATwIZ77_wo2ghSd2EMEUMDAjTIHybQWZUbpbRot4g9IPMSlRaKnJJlc
iStzox02cCpjgwY4ouYef1XqozbGgM9wNRxbo2OSRg64Al8efRYAx-IkacDmtxuGbava2p9R9zK5cQKJ_0P6BbbPMBfbBSWitJutC4ktyWKCPO4Guldb3m
}

GCPEntityColoring(AutoMLTranslation)
!define AutoMLTranslation(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AutoMLTranslation, AutoMLTranslation)
!define AutoMLTranslation(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AutoMLTranslation, AutoMLTranslation)
