sprite $CloudVisionAPI [70x70/4z] {
xPT5eiDG30CbtV_Edx5WEUtisjaKuamCeQSbJvo6Ejc0IE9Q3f1CjY2I6B44aSH3Qu5a4a1Zn9AZ898OiGIHn1TQ2oIJ01eZbjpALk8nKUyihTwrHD8Y6I_o
TKsc1dHDbtWuMBNysNcXAOdyDVhgyJnAThEIfcg-zsyQgoMYTrfLroM-ybq79Nz_p1fl2j85upyqDDUN-f9Bo7NGlIcMqZHzGCC9kPzEkJpsrr7NVE4ITjzD
rJKYEX3YVY9lyiqSbO7jex58a6SZeH5XiGYDYDSWG-zrG3BG-owX4M6n28s8fOsXjHgGZ2OOYm39kYOBqAZIFTO3y0e
}

GCPEntityColoring(CloudVisionAPI)
!define CloudVisionAPI(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudVisionAPI, CloudVisionAPI)
!define CloudVisionAPI(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudVisionAPI, CloudVisionAPI)
