sprite $CloudNaturalLanguageAPI [70x70/4z] {
xTW5SiH05CJGLj__pc6q_yAK5OuA5_pCDBco_-YbShbUauAKd8rMM9XUcu8KHQc2b9LDkxumhS2WA5rDGOgYL47AcKqxilClsTGrPMPGbAufCxFxBz1ziFit
PvNE3Vz-gQEIRQD2dc9L6HUcXvGEYAwmhRFIuRlLVTIMXEDAameAQTUtxj3tKL2KE0hAFegW9E6mefoDTQuCXe9nnMoUuu22V0y8obqj1nJZRcyeP9Fo_1Aw
7j9pdR0mqlEkmSHGYC74UBL1UbSJ5aPwXpMO6A_bH62CGG_o1xe5
}

GCPEntityColoring(CloudNaturalLanguageAPI)
!define CloudNaturalLanguageAPI(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudNaturalLanguageAPI, CloudNaturalLanguageAPI)
!define CloudNaturalLanguageAPI(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudNaturalLanguageAPI, CloudNaturalLanguageAPI)
