sprite $CloudSpeechtoText [70x70/4z] {
xTW5TiDG50DHZVQ_vpARNdscc2XCDuRF6UOQUfG1qaaKf1pkZh0ndKP1Yg9KGShEeHKsfXKO5AMVZO8KHQc2b9L3AsnCAp0eIizcY1nyZg9qW0mKDWujm9O2
mFh6hFmx2sLxonQ8hJmzJ9GktZkba31ItZyiVr51GL7QNwIWA74K18L4AIz1gG4H5ADbC1IC5hC7lT5CGUu3mcb5wXiD9eP232R6C0XfN2TiZ3JUDPWO2Z6O
65CRfBcQi37I7DPWOapBYS0OYnxa0d8B
}

sprite $CloudSpeechtoTextParticipant [50x50/4z] {
pTH50iCm00D1QV__wDvJqnQZIt3CTkuV9ga5W0Rm6G6Iy7611bGB1i1KKf2LW2JLOlnnGJWMrO8da6HqTo7LWgj8CXSaZCJ0lYwe5cYHNuX8uUV3hn8h-kBQ
JUME6dzhEnBwPF32ajWZhc-Ukwa5YHSHG0X3OaLZIIOfu-JNUG
}


GCPEntityColoring(CloudSpeechtoText)
!define CloudSpeechtoText(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudSpeechtoText, CloudSpeechtoText)
!define CloudSpeechtoText(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudSpeechtoText, CloudSpeechtoText)
!define CloudSpeechtoTextParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudSpeechtoTextParticipant, CloudSpeechtoTextParticipant)
!define CloudSpeechtoTextParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudSpeechtoTextParticipant, CloudSpeechtoTextParticipant)
