sprite $CloudJobsAPI [70x70/4z] {
xPS5aiH030FT_l-V3nVZYgARql6gAE1foybWcNg8Ff81QKSHIEENiswcNKKWJOJI2X8mGtV0J7S0GuJI7rK4qaGeBI7hPkWL2Ilh628KKJiWC0w4GxCSKd3i
7WLuln7z-Yw1Y9DMDcymqaqnteXyyjMrR8rHLavD0Kv04Op6dzgV7kv4YxyyEgOmi_DuKZYnXNu6XGX5VbsVWajHlKjrnqdPpyaEVRmm1wvkmkfmj25wQi38
HsdCbLCYqfXHXrIKisQTRaKCOa1j2rE9FCsCjOWH49VIw1_GAwh4DeZGlYvW9hJVJM0gGQ4Ic4eSRGYTrG9cIYb3gG34heaAOCeGXf4_hsS
}

sprite $CloudJobsAPIParticipant [50x50/4z] {
pTG54iD034DHIVU_SvdxdOxABiQUboph_oD3U0Hpr23f1OEIvEqYDOXh4G3DGvoK3qbAubfmcpqJAd35dFV2a30ufuXm3l-V1G9jOo31Z0uVFnQMhiOAnWiQ
TIqSY4ge5cq_87CjSFGvqq_X37XTUQfwUUr2TLZIrsCbBDo7RUYAcCpZh_uiQOdQ8yuldhjo2wHUg025Q8XQORM4mJp4-dQi0G
}


GCPEntityColoring(CloudJobsAPI)
!define CloudJobsAPI(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudJobsAPI, CloudJobsAPI)
!define CloudJobsAPI(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudJobsAPI, CloudJobsAPI)
