sprite $CloudVideoIntelligenceAPI [70x70/4z] {
xTX7eeCm48DX_Rh_dLyl0wuGxH9jw1-3wTPcNi6hi4QyamXYbeSJACQxYI0ceZY2c4dJ1egn0mmHnLSJGKn4SGGndQOD56C762AAxsQ8K5AcrWqyuLdKEq2i
8tDUo_IBOQhuf33OQQ_6lztO75ORh2yFb3fMu4sbLb2L-GQzcVqxJNs5uLMh2uhBh6wLUmgQbR6dNBiQxohQLPWfXmacIWy6gDkjssLsfe4zXTuyiBbslOY7
hztLRN6-ZnWhcjxJTBaQZHM0SXoJvmlwIUHP9uOAPTBT47u72DzDwDsOO9HGK89HuZE8q7TTe9ZGzsw2KK912KQ9Nnj2_sg1OaB_i0b6YTzo560IdHxe2V8E
}

GCPEntityColoring(CloudVideoIntelligenceAPI)
!define CloudVideoIntelligenceAPI(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudVideoIntelligenceAPI, CloudVideoIntelligenceAPI)
!define CloudVideoIntelligenceAPI(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudVideoIntelligenceAPI, CloudVideoIntelligenceAPI)
