sprite $CloudTPU [70x70/4z] {
xTO7hfin40FX6Tx_q47RTAtq3A8cTBSN7-Y_yvZ_CRTmJrvIGUBrxnJAv3KL95QKR4YXZ4cXJ59Wh2ZvQYf8h2Yf897VOb8eanGO3nE9m7ouANbJTYOVArwK
nutXomXiPNn4zib7Ofy-yabmUYSVAyoFU5Aksv80KsLH1A-Rjawnyt3EIX8IuQRuLqKTPKGCW9ebopgIN_A18X6dqb5nLm3CLM6fCyWeu6dQNPb6go8iobGH
F2f7dqacuhu7S5B67sPNE2cFnv7AySKZVuAoJLeuxcxd29Lvvde8gPpLw2Xyg5Ik6QJ1qBWCidHTLoXJkjvjC3GKQJ2SOgCADAg03GGw2XK4yn8fC5npT-GV
o3S
}

sprite $CloudTPUParticipant [50x50/4z] {
pTI5bGGn30JHwie_vsEMjM_xMCFmpJR_FrmYBL1heDyZj2H-kx06fXOEq6KIBJFHakJZ-vTJ5k6LmZCGI9vFvyglzTi-LaCK84Cegg97uHJiGjXwri3ulecN
r7FuRdIfHpCvDP57DWL70NYbqBo8Sys5AK9m4y25KS2nFs28IyDel4Zu44b6__PZbzGpYbvmfQ1VIrf2kyJbY-ikQG7qWW8KeY6q8hI49U8v-Esu1G
}


!define CloudTPU(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudTPU, resource)
!define CloudTPU(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudTPU, resource)
!define CloudTPUParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudTPUParticipant, CloudTPUParticipant)
!define CloudTPUParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudTPUParticipant, CloudTPUParticipant)
