sprite $CloudText [70x70/4z] {
xTT7OiDG00BHWVlVERqNWYHsyQpbP_pTARib_rM1k6c2MCJaBc9kco3MH7521cDa3yRO0qOJnKUR8DP4yGInqj7sdPaYAJDgxpWg9P8PdrPqNF4FboQaLyHB
oezKA2Zc9KS50Fskk3brdZkgw4ELOe3kK1KKWQuh1WyK3PJseuUzyXEbYT8iB1GD5C500NHQwJzAGUzA_1IebN23Gug-NozUQiyblqfrGH5lNL2W7IEU2qWv
9a_f6IKaApcnO5Zy3DBeTzrWpEZtxe9XeOW5m-AlZKR_rGPZI6qK9WXoanWmX5f7_8Fk0G
}

GCPEntityColoring(CloudText-to-Speech)
!define CloudText-to-Speech(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudText-to-Speech, CloudText-to-Speech)
!define CloudText-to-Speech(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudText-to-Speech, CloudText-to-Speech)
