sprite $CloudTexttoSpeech [70x70/4z] {
xTT7OiDG00BHWVlVERqNWYHsyQpbP_pTARib_rM1k6c2MCJaBc9kco3MH7521cDa3yRO0qOJnKUR8DP4yGInqj7sdPaYAJDgxpWg9P8PdrPqNF4FboQaLyHB
oezKA2Zc9KS50Fskk3brdZkgw4ELOe3kK1KKWQuh1WyK3PJseuUzyXEbYT8iB1GD5C500NHQwJzAGUzA_1IebN23Gug-NozUQiyblqfrGH5lNL2W7IEU2qWv
9a_f6IKaApcnO5Zy3DBeTzrWpEZtxe9XeOW5m-AlZKR_rGPZI6qK9WXoanWmX5f7_8Fk0G
}

sprite $CloudTexttoSpeechParticipant [50x50/4z] {
pTH5biGm00FHakv_wDaC6PHdDTSs-G4Jdvz3YY1N0_inmYw97ovS0wiMhi7u4jdbI-oIo2b0Et45m2jn33nSLYqy0two1Mo40RGL00GHlsSh37wwiC8ooC87
ObmK_1VwNnQfA2W54BxgJp2AWV2l7w7DBTV2WcNndYpSyPaw5loK145aaW4-YvRG7d6wyzn5BO1UK812D8HMY9OGalVnwhu
}


!define CloudTexttoSpeech(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudTexttoSpeech, resource)
!define CloudTexttoSpeech(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudTexttoSpeech, resource)
!define CloudTexttoSpeechParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudTexttoSpeechParticipant, CloudTexttoSpeechParticipant)
!define CloudTexttoSpeechParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudTexttoSpeechParticipant, CloudTexttoSpeechParticipant)
