sprite $CloudAutoML [70x70/4z] {
xPU5RiHG40Dt_F__NERMBsl95TrPSB3HPEBmB7CFkie2eaqg495lJYwZRIeGKQ4eWkGoA4cWacEeK9Ic0X4LYYeG4LGRo1oM-FXnYU62mefYvfdCkJWaOOmv
gonTbAZeuujTaa35Btg007eE03fX0dv4ERLkCAOm0p5xsrRhHlgTLCN99zMILNvkFRdq97tPSecEKYSJRQfPPwQ2Em7IeuZ_EefqK94R5OyYCmskqFxeuvho
CQAXCkDKFhxurIscsHrdTbl41MLMxHf89hDuWAaylmpAG-cvhY1JUjvjOAP1OHgOSI5NwR-hvJAzTrYV2cH8g_MOt2JdC3UGHm
}

GCPEntityColoring(CloudAutoML)
!define CloudAutoML(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudAutoML, CloudAutoML)
!define CloudAutoML(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudAutoML, CloudAutoML)
