sprite $CloudTranslationAPI [70x70/4z] {
xTW7ha9134FHQ-z_pxzNSCG4MHMYXjh1cQx7OJrBlbK7Y4-gWbZxTlPXV5eLnAeehY1p6Dc5C7Q1KKNnjYg8LL6Sa48OsOKmTe5HHV6zLK6iYk8PaRGFe-3l
mtYX09dnKb5KDXi3XZ3UARfM15gk3iSmeNEDOqDMb1H-iVGFSBW0BgDyYOBZrIIG8Cmlaw9nDLvEccrmRXOFJ1XnvWMWZA2hnBCYEDvU0dqMA6oBiCQ30-Hz
1a1kHbTzWN87032e0EJc__44PTmVGFojrR4hvICrt4RxKkaEA8GftOqDXeOY6WoDPv1Axxf2cD9xjy7GK4I3OIerea0Z2gY1G4UXW1pt90fCuwE7U81w1G
}

GCPEntityColoring(CloudTranslationAPI)
!define CloudTranslationAPI(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudTranslationAPI, CloudTranslationAPI)
!define CloudTranslationAPI(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudTranslationAPI, CloudTranslationAPI)
