sprite $DialogFlowEnterpriseEdition [70x70/4z] {
xTU7RWCn30DGal__qSNCb6aQONU47V3UURI23c6zYzfLW2Yf2Y9kjrDOZDAg8695KGKHpT4M5YCL65OKgS2uQ7x0DiXmCRkNHOlXFXCi9bakTo5cVvhqIlo_
HiEaXi-Uj22kmgyq3oQtdD_sep0xbzSzvcV_aXuD8bGklmsRMJzWxC4O3vYRunh8uGcjbCiBBWUoLEWKW6cJiCh5UNaWc7vvB8QztIleA2me10eA01uhumCT
1OSAnto-6D_f5Je-oxnZkcGuLj3dgCJPXhHdT9h9UmfE5ARZgilaansNoj7al0WT3fcS56Q8NymNZCreA4I3GUFJXgLljS9YuAgZe8A0uT4M60k43l4FwWC
}

sprite $DialogFlowEnterpriseEditionParticipant [50x50/4z] {
pPK5jWGm20C9zx_pbrKgcRUivrabKo_4zokD182J0KZF8P85mDE8R0EfO48XdcGx7aqYCvgVn7R8z0Wsk2VC1BuN_DCI11FZkk3OrzvvsuUA9hygjKnwyjGD
B9PfpigK5YPErbgl4ZoFNW1Gfdj4SB9F8w99n3r4j8ZD20nedLIyRVgQ_DFX7bsF2JEv04nm85q9CH2Q277WNK_ubk2kR2UGFX5De4yyFpihkaWO2VnlrIy
}


GCPEntityColoring(DialogFlowEnterpriseEdition)
!define DialogFlowEnterpriseEdition(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, DialogFlowEnterpriseEdition, DialogFlowEnterpriseEdition)
!define DialogFlowEnterpriseEdition(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, DialogFlowEnterpriseEdition, DialogFlowEnterpriseEdition)
