sprite $CloudIoTCore [70x70/4z] {
xTT9bc9134DHFUr_qJMYnt9mlcQLogGtDyAcrs7-WhUWDJv91J5hEuND-3GLn5GKLn0JHblOZ5rWg2Z-DHN4L1HN41D6Us4poseSCQn5kn9hpajEXiTQau58
1KHpnlLOva5a8d_FEkLuDRmf34nIkDz-EudrlgmWuR5HlIWoWsB9vyg467bWLcLFKFn39WL_3G5wRHg5sev2GK4gA9AugeJ7ZljDQ2aDpoC9Foj8K_jAogq7
TEzFIk-yWo9nlwl4eEWMGgzFftahunBt-OI7S_si6UOn8R5gUUuVCIoBd2actxWpUzJu6aJfUrrXCwNlkmr63GKr64sXi9NMRpNHGAIEeW9ot1CgC5gpE-W_
o3y
}

sprite $CloudIoTCoreParticipant [50x50/4z] {
pTG5aiD044FHBzt_palXTAjSMbOuzXkUuV_78OeWfmRszmYx9FvsuHfOjV00NIMooqhMyfG92fUIY5VoXTI_MR-c43Epaj0UHQBdAavl9wmXzjy0fxTHfc6E
nTsxl8oC1ndEZ-HO-213Z1iMStiNzZS8IW64lyYNMNhkam2Z0OQGTHMZrKghtGRM5foY9w9hsm9W7-7rxqmWW2WiYkCdXlQ8qnVFNTG2w0K5A4H3Q8Le2I7o
7duxhm
}


GCPEntityColoring(CloudIoTCore)
!define CloudIoTCore(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudIoTCore, CloudIoTCore)
!define CloudIoTCore(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudIoTCore, CloudIoTCore)
!define CloudIoTCoreParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudIoTCoreParticipant, CloudIoTCoreParticipant)
!define CloudIoTCoreParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudIoTCoreParticipant, CloudIoTCoreParticipant)
