sprite $Slack [70x70/4z] {
lPT94iD03081_V_FEQMKWxneeDAdh5spWMsWeUezmeHg3or7Wr_gd8YaDULXItgtL2uz55EZYAK229M0bK0lunBPI5-3X8OHYqxBGu7G0W1d2_kx5nA0rxq8
7cq9chTpaskP5nEmBSI0LXPYXDjhp3mRrwAgW6MHFNSimenMMPeLoqJUJ87zVcqPllkNHTCfdQR4swdn-yExmN0pjtmzpCVnn2B3CYhsnxWLZaLMkgreDma7
SOEZQ8ovg3UBMqahtAxows5EGKMwQh536eg4Y-l9MFpzNVmfpBVaxvSLiQ0UDULQIcGjB1O4omT0nW9Vah0m-Vo4Y0IGDPt6IreZOnmV
}

sprite $SlackParticipant [50x50/4z] {
pTHLWeL050FHIhB_DO_RVLXdl7xGWzEyvfmdHbdAlAQiDgwd84fAaguQHAIj5_w-W_7O_n3M4Cz45yVr53ocjIlXGzyjU9qh15o3IMOvhGJivkNztrQjYIIT
6EjS2vBikvrhNtfeVEtRKlTjYP4kXBxuwfspnBPcTtVVbZ_rfQWMMH4kHBnpxSQvYcyUSrKBifTmBaGHRW7qWXf03Q06e6B_Um
}


!define Slack(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Slack, resource)
!define Slack(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Slack, resource)
!define Slack_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Slack, new_resource)
!define Slack_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Slack, new_resource)
!define Slack_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Slack, modified_resource)
!define Slack_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Slack, modified_resource)
!define Slack_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Slack, deleted_resource)
!define Slack_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Slack, deleted_resource)
!define SlackParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, SlackParticipant, SlackParticipant)
!define SlackParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, SlackParticipant, SlackParticipant)
