sprite $Slack [70x70/4z] {
xTG5SiL040FHQTt_pc4qzQx7uQZumokjGNK-_m7W4WGkGU0xAVmUPSa0-difOyLuoe72cuZ2ha93gHc5Xk8Cj1MWhM28CuZXYXEkAD5cwX85DzfA5bd-4sT8
zfNHhKfsbV75osQMlp-dJCulKkIa0Z3FR16TCbJDA8Gri_YnC6pS1QRcjyXBE3dYyaYCC4cwIfAsaeZYJ9AkaWZYIYA8Cawu8eG49q9fYCUC3AL1b1nfzAPw
6I76bA4ReiCYBSRA2D9JCgSmMwQi32NA3hBy7cEelP0mSdv_6KMP3DSmtqb1Dc2oJFLYoBXJFost
}

sprite $SlackParticipant [50x50/4z] {
rT853iHG30FHRz__q2jOIfsHoZ3Y9gyy7fOaBGPCMEXo8JL2_18ajOIl5eSrYMvxFed309B4-YoXYDuLDzfudLfn1TkpXVpNtnu9kVHTOkBQTu45W7cYp9bC
7ddsHSeyn7ThzY_lJo62bFLP5odhCuGZ48hr07aHTscGS1l_zB0FoTZyzO62Jfo2mMI28ESNY3ZSpFbTbNSSCov4j5s818U2A-2ANW
}


!define Slack(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Slack, resource)
!define Slack(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Slack, resource)
!define Slack_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Slack, new_resource)
!define Slack_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Slack, new_resource)
!define Slack_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Slack, modified_resource)
!define Slack_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Slack, modified_resource)
!define Slack_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Slack, deleted_resource)
!define Slack_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Slack, deleted_resource)
!define SlackParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, SlackParticipant, SlackParticipant)
!define SlackParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, SlackParticipant, SlackParticipant)
