sprite $AppEngine [70x70/4z] {
xPS7QWH140DB_Vy_EtlJxAa5ReBj4_b6LzH4MC8ye-f2dqeo0YcrqncGgJGZaD88fKOW9RUqUGAL59Eho51Y5JEIG-I7SXN2bV7DN4O1PKsiui-0KycJ7pXP
J01HrF0T9RfT8Tj6RSFjxgZjGN9Er64UYoxbXEB_up7nJPOfgy4BK7sqpChSeQk0otPlwFj_hDe72cZp-VgrltQ2AsKpEb8WeMYZAA9en8LrRzPruR8koy8y
tcdTxz5TP8xZScFTJR836yIf1FU8evP-UXtbclO-ei1Qj1Zed2jzKN4GnU-xku11fTGLd6qU9Z1CKCG4XciqeG83AaR6GWPacC0mGH4J62O-RJJqhJOWWyiC
XG58F2SnW2680f4_drS
}

sprite $AppEngineParticipant [50x50/4z] {
pTC5biD030JHQjt_pelXgCPFuGv7_XxcyrEIAF0eyCo50e-2kV1iWiWKgu1b8trvsKX4I2DMZ1DI4XNztdE25NpmpTz65Eo-2SbYNe56232YsmDIgSg621NO
0I3_5s1R563NZTqREo678QSYHv4BGI_mDcJa_4UcvZoGNNlGpAx-0y3EZvQmgSfkYzqk685bAKQaO0iwEBOUxX6C0Qdj18QDmB0HODW8Ky9SJ0bJ4QO4IUpw
L-SR
}


!define AppEngine(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AppEngine, resource)
!define AppEngine(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AppEngine, resource)
!define AppEngine_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AppEngine, new_resource)
!define AppEngine_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AppEngine, new_resource)
!define AppEngine_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AppEngine, modified_resource)
!define AppEngine_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AppEngine, modified_resource)
!define AppEngine_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AppEngine, deleted_resource)
!define AppEngine_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AppEngine, deleted_resource)
!define AppEngineParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, AppEngineParticipant, AppEngineParticipant)
!define AppEngineParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, AppEngineParticipant, AppEngineParticipant)
