sprite $AppEngine [70x70/16z] {
xTK5TiL028LXHhcriF_LFcUg44x3qVQlo_jY8nBiF-mNCH8OP328be2aAKX0qXIa84X0b8ahx31XXAWTLvY846PWL5CKkbIY33o546COHerAAr45losCy565
wL4DC7k6zvnuHsdqkOaVyv6YptYT5RkCVIPOJPjn45PaPO--BuZ_6lDHRQf4Pl9mJcRlL3eH3VJ7BzbWyAr9jnSixlx4ro91yDD3Vr0QyUENrw_wfpBXnJfC
LLbVg2pbrhxIm4lfgf2ZXC_5LmIVghS-Als135NgjUugsdgef06mPxRuAtzNP7ZZnPi14q1JH6LBsSnrONrJTLOF0mbFnsa-NnQRcVJfsDLP61m5l9PjVwHj
4c0q2q5efzU6YoZZdazXMENii3bA1YCP2ai68vB0I8wImKYEai58XY9MEShJCKJBKROuuXL6_78KIK1YZFo1pW
}

GCPEntityColoring(AppEngine)
!define AppEngine(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AppEngine, AppEngine)
!define AppEngine(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AppEngine, AppEngine)
