sprite $AppEngine [70x70/4z] {
xPS7QWH140DB_Vy_EtlJxAa5ReBj4_b6LzH4MC8ye-f2dqeo0YcrqncGgJGZaD88fKOW9RUqUGAL59Eho51Y5JEIG-I7SXN2bV7DN4O1PKsiui-0KycJ7pXP
J01HrF0T9RfT8Tj6RSFjxgZjGN9Er64UYoxbXEB_up7nJPOfgy4BK7sqpChSeQk0otPlwFj_hDe72cZp-VgrltQ2AsKpEb8WeMYZAA9en8LrRzPruR8koy8y
tcdTxz5TP8xZScFTJR836yIf1FU8evP-UXtbclO-ei1Qj1Zed2jzKN4GnU-xku11fTGLd6qU9Z1CKCG4XciqeG83AaR6GWPacC0mGH4J62O-RJJqhJOWWyiC
XG58F2SnW2680f4_drS
}

GCPEntityColoring(AppEngine)
!define AppEngine(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, AppEngine, AppEngine)
!define AppEngine(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, AppEngine, AppEngine)
