sprite $CloudFunctions [70x70/4z] {
xTP7UiH044BX1_U_itDsqq5YPxEOFFz7JIY9pVn7NeLrl9CAOYt7APJnRYg8LL5SGN8P-IIvIe5HHV5fAeXLKJn22cLa5yhuMXPLv46qK0OJ3n1GO08I7lp5
A2iQJWaZUucCtw1GHW7POqALWCIXygJoE6UAG_8RRYi2tLSCBYYQAQ2FIw6is5a1UByKeCkAlboI5QswwCjbLCYA9J_dosLKLFcEA2Y0Aly0EWgZ1myKiiBs
VX6G7pvQKdcLxY7Y8xSsOofZRQ-lysEZWrmusXSKqM1ed0QfT5vNA5CwtsqmD1JHO4XHemeqge0Q27GK2iZsJAB04BFlY3-GHm
}

GCPEntityColoring(CloudFunctions)
!define CloudFunctions(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudFunctions, CloudFunctions)
!define CloudFunctions(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudFunctions, CloudFunctions)
