sprite $CloudRun [70x70/4z] {
xPS7RaDH3CC-VVyxTnkxeWC8Esgp4tx9RpytlGKZ0eVCGJYaW9cZp4h1p9mbLewY0LbCd-AGEsPUb5Wv2h5ob5Wv2e4SHQQmZqB9Le3VH_58B2tBjQYvAliU
KZ9YAoyQgtni89QzNt0pZ50CitbIf10hNsVDR6ib36jbSYIfybgnI16p5pGpJERi-nOfOzXtSoJ-z5y5o1q17_uxz3sIShXIuh3h97gykZxB7rew6zcllaG9
hi-12CFnR8KqDN2Z8DCK4aWWgyACMPYz2oj9OrMhhB2osiznjVUTXwkm8IjjfgZi3bixrOAPqWw-WIaSiae792edljBfiu4fdSeB61uJ726kjpu1
}

sprite $CloudRunParticipant [50x50/4z] {
pPK7RiG03CDC___F7UfkUPUecm0oZ11Izlnxs7MeX40b17h3XLBP0wg8G1KHgeY028sohS7B51wN0XeHFKj1puBiCkeW4HbcgOf4P4XgpO26H91Qf9agCjib
cYZZionZMuKDLclNOWOpnczm84klvGhKHj_gufdByU7ArNK17sKPi7kEbd9XkV8aPcs2F-thmbvze-pUKh-r_cN8Yk9ZSerf3VglQF-bxly6PSZqVxLM6QEA
25H2e10K7fdVvnO
}


!define CloudRun(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudRun, resource)
!define CloudRun(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudRun, resource)
!define CloudRun_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudRun, new_resource)
!define CloudRun_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudRun, new_resource)
!define CloudRun_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudRun, modified_resource)
!define CloudRun_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudRun, modified_resource)
!define CloudRun_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudRun, deleted_resource)
!define CloudRun_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudRun, deleted_resource)
!define CloudRunParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudRunParticipant, CloudRunParticipant)
!define CloudRunParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudRunParticipant, CloudRunParticipant)
