sprite $CloudFunctions [70x70/4z] {
xTP7UiH044BX1_U_itDsqq5YPxEOFFz7JIY9pVn7NeLrl9CAOYt7APJnRYg8LL5SGN8P-IIvIe5HHV5fAeXLKJn22cLa5yhuMXPLv46qK0OJ3n1GO08I7lp5
A2iQJWaZUucCtw1GHW7POqALWCIXygJoE6UAG_8RRYi2tLSCBYYQAQ2FIw6is5a1UByKeCkAlboI5QswwCjbLCYA9J_dosLKLFcEA2Y0Aly0EWgZ1myKiiBs
VX6G7pvQKdcLxY7Y8xSsOofZRQ-lysEZWrmusXSKqM1ed0QfT5vNA5CwtsqmD1JHO4XHemeqge0Q27GK2iZsJAB04BFlY3-GHm
}

sprite $CloudFunctionsParticipant [50x50/4z] {
pTH7SaD130FHHj__q5wFoN4Lh8WTmvD-vllZ9Mc1MWDzZj2I-7HX3Kmj7A3xasZv9rgIrEBiUYzt0FSoG-Gi9nb_CS1ASjR-pXHMGl3bmYnJKC308fmY405P
1TV_YAwYFmye1T0B_XOP6wEUWBESP83vWcIGMzc_W_sNeHSjeVt4vS7lBca1z8825A8Xj2AqX4lY7jwT7m
}


!define CloudFunctions(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudFunctions, resource)
!define CloudFunctions(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudFunctions, resource)
!define CloudFunctionsParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudFunctionsParticipant, CloudFunctionsParticipant)
!define CloudFunctionsParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudFunctionsParticipant, CloudFunctionsParticipant)
