sprite $ComputeEngine [70x70/4z] {
xTW7SiCm50DHBEv_v_GU-ekHTceCTvFpMDILpTn3ZvBZT2SAKWw78tIckr6GeYXLa39ChT2PLc1GbFur2b8KfGfI5bChTAOL61JbLfss2It9CTFJ2ehI6M5p
6s4gx0APA_QIqW7fxu9P6GhsQ_UoGaB74V6QjftgTbJ8QnWL36KWVYZ3l6WANGLOAa1NSUOb20h9CAAVBi2D5b6sW3XABcxJolw5zz9BobmA943Utc7eYdSC
2ASLvzZe7EqDXHXCZDCWfFCweJFI-Qx1n528mSIuj46wLXCw8rt36aoCot8YCCPD3_8FyWW
}

sprite $ComputeEngineParticipant [50x50/4z] {
pTG53a9148FXjlU_CnB1EflDZpSwyi5p_N-oYBUWWq7o7f50ahUBO11ZaGBiJvp0FqaWCHOrSQAa1mMsmgFGNJmDinRprDNBDQFepcOXzx4VX3s9RkcSUMue
EjA3ACEFYWj-TPyHGlSSFrSUc_jdLrwy7rPM_my4_J9mGOde9yulVdTb2YGk100GX8WAYn8juipHjtC4
}


!define ComputeEngine(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, ComputeEngine, resource)
!define ComputeEngine(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, ComputeEngine, resource)
!define ComputeEngine_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, ComputeEngine, new_resource)
!define ComputeEngine_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, ComputeEngine, new_resource)
!define ComputeEngine_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, ComputeEngine, modified_resource)
!define ComputeEngine_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, ComputeEngine, modified_resource)
!define ComputeEngine_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, ComputeEngine, deleted_resource)
!define ComputeEngine_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, ComputeEngine, deleted_resource)
!define ComputeEngineParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, ComputeEngineParticipant, ComputeEngineParticipant)
!define ComputeEngineParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, ComputeEngineParticipant, ComputeEngineParticipant)
