sprite $ContainerOptimizedOS [70x70/4z] {
xTS5RaOn30DWs_U_ytZpe5vIoSBDeWVfr_I71rZcFzGKpD4c5KGSbrDeHjjK4B6Yg8BaPgYRv5OA32kARbD1n8gY4r9eXaCPLyqiPfePRXQDgIWsGdedC3FY
8x7GEP_JrnDd9Y0UO2KpReO1-Que5MTUxueBfD1uFAmtnTtQNody60OdDZCV11mVuc5Q1kKRmz_drVTuEjgH14Q59yNTK-AR0NWt92d0jv_MMd6T5sC1HuL3
Bm3bmKd1bI85XIU5TmhphouhQTxysxMI1mp_8-b3kVXJ7qe1QlvFv-kBBqjUGgnEEgsjhdNvpCrrDv_YZ0WEpmpdg-juRpH4tjnYx-_JbMS63lE4w-xKBtKV
bfxh2isKddSR31eAqM2Gma8hhNSri8407GK5PBqcei1WpEmGVo2F
}

sprite $ContainerOptimizedOSParticipant [50x50/4z] {
pPO53aCn34DZt__EuvLSJ_8um-JhXOhr_q8Zi82N623VGv0XmhSJZ04Y9YX05WJw66hp8U0ykH0-tRqPtGK4SG1hr7RvhW07ou9eYAjw-NW4SuYBcTqLbD0G
77keGQXgBz0GcbHBjw1UiKqA3IiXQCguZv_E2LluzRiP3G4XjjrHpSUmAYw4wQvCgnQiOCPy5sHiZyvKjQ0AZ-TkmKQ50C-jGM_sJ_nUGbfVyNvL2FR4PDyD
W-JdHtwgnSJdJsUywSxWMrpVbYC
}


!define ContainerOptimizedOS(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, ContainerOptimizedOS, resource)
!define ContainerOptimizedOS(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, ContainerOptimizedOS, resource)
!define ContainerOptimizedOSParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, ContainerOptimizedOSParticipant, ContainerOptimizedOSParticipant)
!define ContainerOptimizedOSParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, ContainerOptimizedOSParticipant, ContainerOptimizedOSParticipant)
