sprite $KubernetesEngine [70x70/4z] {
xTO7RYDH38FXdxp_dRUlNAadOuIQ46MQy8LAui8mtv5FuHnFie9OntKModYQ5SHQKRo2v3Ao5yhO2unM57-Q5SHQKHoGgsNKJOxB7EPcZ4v3cYZDsaBbz4ms
R64hJ_LA_NnHbxHbSf5IYerbr1YbnBLY5UvfeFI6URjhdHB8YQAdfGbACSuAzycAG45vPfmLWxE2hJ94LjGg_7DaGwFOlO9iRBYcW0mdHKU5WSAEeWL5a1Jn
f10LG6yL0RvNwivR9DwkfLphTEDq3GM6-_c0q5UKrLONBQF9pQe2yjbHV8UkE3qz6JPKb9_dPS8RMLhhuaUiVNm-Kgp3qo5ZqFpBbFnvjFIzRg7CqlVT3OOD
HMmmf6YZ2cnK0MqWiAEmW8nt4WiCm5L7V87y1
}

GCPEntityColoring(KubernetesEngine)
!define KubernetesEngine(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, KubernetesEngine, KubernetesEngine)
!define KubernetesEngine(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, KubernetesEngine, KubernetesEngine)
