sprite $KubernetesEngine [70x70/4z] {
xTO7RYDH38FXdxp_dRUlNAadOuIQ46MQy8LAui8mtv5FuHnFie9OntKModYQ5SHQKRo2v3Ao5yhO2unM57-Q5SHQKHoGgsNKJOxB7EPcZ4v3cYZDsaBbz4ms
R64hJ_LA_NnHbxHbSf5IYerbr1YbnBLY5UvfeFI6URjhdHB8YQAdfGbACSuAzycAG45vPfmLWxE2hJ94LjGg_7DaGwFOlO9iRBYcW0mdHKU5WSAEeWL5a1Jn
f10LG6yL0RvNwivR9DwkfLphTEDq3GM6-_c0q5UKrLONBQF9pQe2yjbHV8UkE3qz6JPKb9_dPS8RMLhhuaUiVNm-Kgp3qo5ZqFpBbFnvjFIzRg7CqlVT3OOD
HMmmf6YZ2cnK0MqWiAEmW8nt4WiCm5L7V87y1
}

sprite $KubernetesEngineParticipant [50x50/4z] {
pTG5OiD034JHFtF_EnV3-WKLCy5TwPbjxZ-j9njmo1gqU-5WIVhZeclGh4K5R5OIgR-_4brUtY7n4cyBAPHAnS5X1jkq377HnK5VcmdEOoud3l5b77ulg2no
Y5mUmzaXOxQ2WscGbfY00pDH5r1mmLy8nf0BWNICCMaFeWNhi2M44bicGyWYCo_Ucl45-2q8nFlxxZtO7AGArlSv7V598H87fEi7xtOLa2s0lM015c93s8gm
9U19FVnr7W4
}


!define KubernetesEngine(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, KubernetesEngine, resource)
!define KubernetesEngine(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, KubernetesEngine, resource)
!define KubernetesEngineParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, KubernetesEngineParticipant, KubernetesEngineParticipant)
!define KubernetesEngineParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, KubernetesEngineParticipant, KubernetesEngineParticipant)
