@startuml!define GCPPuml https://raw.githubusercontent.com/gamma-data/GCP-C4-PlantUML/master/templates
!includeurl GCPPuml/C4_Context.puml
!includeurl GCPPuml/C4_Component.puml
!includeurl GCPPuml/C4_Container.puml
!includeurl GCPPuml/GCPC4Integration.puml
!includeurl GCPPuml/GCPCommon.puml

' COMMENT OUT OR REMOVE THE SERVICES BELOW THAT ARE NOT REQUIRED IN YOUR DIAGRAM
!includeurl GCPPuml/AIandMachineLearning/AdvancedSolutionsLab.puml
!includeurl GCPPuml/AIandMachineLearning/AIHub.puml
!includeurl GCPPuml/AIandMachineLearning/AIPlatform.puml
!includeurl GCPPuml/AIandMachineLearning/AIPlatformDataLabelingService.puml
!includeurl GCPPuml/AIandMachineLearning/AutoMLNaturalLanguage.puml
!includeurl GCPPuml/AIandMachineLearning/AutoMLTables.puml
!includeurl GCPPuml/AIandMachineLearning/AutoMLTranslation.puml
!includeurl GCPPuml/AIandMachineLearning/AutoMLVideoIntelligence.puml
!includeurl GCPPuml/AIandMachineLearning/AutoMLVision.puml
!includeurl GCPPuml/AIandMachineLearning/CloudAutoML.puml
!includeurl GCPPuml/AIandMachineLearning/CloudInferenceAPI.puml
!includeurl GCPPuml/AIandMachineLearning/CloudJobsAPI.puml
!includeurl GCPPuml/AIandMachineLearning/CloudNaturalLanguageAPI.puml
!includeurl GCPPuml/AIandMachineLearning/CloudSpeech-to-Text.puml
!includeurl GCPPuml/AIandMachineLearning/CloudText-to-Speech.puml
!includeurl GCPPuml/AIandMachineLearning/CloudTPU.puml
!includeurl GCPPuml/AIandMachineLearning/CloudTranslationAPI.puml
!includeurl GCPPuml/AIandMachineLearning/CloudVideoIntelligenceAPI.puml
!includeurl GCPPuml/AIandMachineLearning/CloudVisionAPI.puml
!includeurl GCPPuml/AIandMachineLearning/DialogFlowEnterpriseEdition.puml
!includeurl GCPPuml/AIandMachineLearning/RecommendationsAI.puml
!includeurl GCPPuml/APIManagement/APIAnalytics.puml
!includeurl GCPPuml/APIManagement/ApigeeAPIPlatform.puml
!includeurl GCPPuml/APIManagement/ApigeeSense.puml
!includeurl GCPPuml/APIManagement/APIMonetization.puml
!includeurl GCPPuml/APIManagement/CloudEndpoints.puml
!includeurl GCPPuml/APIManagement/DeveloperPortal.puml
!includeurl GCPPuml/Compute/AppEngine.puml
!includeurl GCPPuml/Compute/CloudFunctions.puml
!includeurl GCPPuml/Compute/CloudRun.puml
!includeurl GCPPuml/Compute/ComputeEngine.puml
!includeurl GCPPuml/Compute/Container-OptimizedOS.puml
!includeurl GCPPuml/Compute/GKEOn-Prem.puml
!includeurl GCPPuml/Compute/GPU.puml
!includeurl GCPPuml/Compute/KubernetesEngine.puml
!includeurl GCPPuml/DataAnalytics/BigQuery.puml
!includeurl GCPPuml/DataAnalytics/CloudComposer.puml
!includeurl GCPPuml/DataAnalytics/CloudDataCatalog.puml
!includeurl GCPPuml/DataAnalytics/CloudDataflow.puml
!includeurl GCPPuml/DataAnalytics/CloudDataFusion.puml
!includeurl GCPPuml/DataAnalytics/CloudDatalab.puml
!includeurl GCPPuml/DataAnalytics/CloudDataprep.puml
!includeurl GCPPuml/DataAnalytics/CloudDataproc.puml
!includeurl GCPPuml/DataAnalytics/CloudPubSub.puml
!includeurl GCPPuml/DataAnalytics/Genomics.puml
!includeurl GCPPuml/Databases/CloudBigtable.puml
!includeurl GCPPuml/Databases/CloudDatastore.puml
!includeurl GCPPuml/Databases/CloudFirestore.puml
!includeurl GCPPuml/Databases/CloudMemorystore.puml
!includeurl GCPPuml/Databases/CloudSpanner.puml
!includeurl GCPPuml/Databases/CloudSQL.puml
!includeurl GCPPuml/DeveloperTools/CloudBuild.puml
!includeurl GCPPuml/DeveloperTools/CloudCode.puml
!includeurl GCPPuml/DeveloperTools/CloudCodeforIntelliJ.puml
!includeurl GCPPuml/DeveloperTools/CloudScheduler.puml
!includeurl GCPPuml/DeveloperTools/CloudSDK.puml
!includeurl GCPPuml/DeveloperTools/CloudSourceRepositories.puml
!includeurl GCPPuml/DeveloperTools/CloudTasks.puml
!includeurl GCPPuml/DeveloperTools/CloudTestLab.puml
!includeurl GCPPuml/DeveloperTools/CloudToolsforEclipse.puml
!includeurl GCPPuml/DeveloperTools/CloudToolsforPowerShell.puml
!includeurl GCPPuml/DeveloperTools/CloudToolsforVisualStudio.puml
!includeurl GCPPuml/DeveloperTools/ContainerRegistry.puml
!includeurl GCPPuml/DeveloperTools/GradleAppEnginePlugin.puml
!includeurl GCPPuml/DeveloperTools/IDEPlugins.puml
!includeurl GCPPuml/DeveloperTools/MavenAppEnginePlugin.puml
!includeurl GCPPuml/HybridandMultiCloud/Stackdriver.puml
!includeurl GCPPuml/HybridandMultiCloud/TrafficDirector.puml
!includeurl GCPPuml/InternetofThings/CloudIoTCore.puml
!includeurl GCPPuml/ManagementTools/CloudAPIs.puml
!includeurl GCPPuml/ManagementTools/CloudBillingAPI.puml
!includeurl GCPPuml/ManagementTools/CloudConsole.puml
!includeurl GCPPuml/ManagementTools/CloudDeploymentManager.puml
!includeurl GCPPuml/ManagementTools/CloudMobileApp.puml
!includeurl GCPPuml/ManagementTools/CloudServiceMesh.puml
!includeurl GCPPuml/ManagementTools/CloudShell.puml
!includeurl GCPPuml/ManagementTools/Debugger.puml
!includeurl GCPPuml/ManagementTools/ErrorReporting.puml
!includeurl GCPPuml/ManagementTools/Logging.puml
!includeurl GCPPuml/ManagementTools/Monitoring.puml
!includeurl GCPPuml/ManagementTools/Profiler.puml
!includeurl GCPPuml/ManagementTools/Stackdriver.puml
!includeurl GCPPuml/ManagementTools/Trace.puml
!includeurl GCPPuml/Migration/TransferAppliance.puml
!includeurl GCPPuml/Networking/CloudArmor.puml
!includeurl GCPPuml/Networking/CloudCDN.puml
!includeurl GCPPuml/Networking/CloudDNS.puml
!includeurl GCPPuml/Networking/CloudExternalIPAddresses.puml
!includeurl GCPPuml/Networking/CloudFirewallRules.puml
!includeurl GCPPuml/Networking/CloudLoadBalancing.puml
!includeurl GCPPuml/Networking/CloudNAT.puml
!includeurl GCPPuml/Networking/CloudNetwork.puml
!includeurl GCPPuml/Networking/CloudRouter.puml
!includeurl GCPPuml/Networking/CloudRoutes.puml
!includeurl GCPPuml/Networking/CloudVPN.puml
!includeurl GCPPuml/Networking/DedicatedInterconnect.puml
!includeurl GCPPuml/Networking/PartnerInterconnect.puml
!includeurl GCPPuml/Networking/PremiumNetworkTier.puml
!includeurl GCPPuml/Networking/StandardNetworkTier.puml
!includeurl GCPPuml/Networking/TrafficDirector.puml
!includeurl GCPPuml/Networking/VirtualPrivateCloud.puml
!includeurl GCPPuml/Security/CloudIAM.puml
!includeurl GCPPuml/Security/CloudResourceManager.puml
!includeurl GCPPuml/Security/CloudSecurityCommandCenter.puml
!includeurl GCPPuml/Security/CloudSecurityScanner.puml
!includeurl GCPPuml/Security/KeyManagementService.puml
!includeurl GCPPuml/Storage/CloudFilestore.puml
!includeurl GCPPuml/Storage/CloudStorage.puml
!includeurl GCPPuml/Storage/PersistentDisk.puml
@enduml
