sprite $CloudStorage [70x70/4z] {
xTZ75G8m40DHQVelcZlHYuUC2lZFEMmMyq-vbGM4bIW8dNTdtXXMeo1KKL0GEXdQUMD0OAeeJACWL55G47fcQ8N6WC1KKRWt2a8L1GMX2qCxQ0m8pEJmwCCK
Jf7B2bnIcdHV8O7j7j6XmlkdYgACBgaoHr7MIxgjUFiesLnroe9i32R6aLdf3X0Q8zsD1XD3QGmcnZEeqhjEQ8pqtZMO64fZC36-DfN-Qa9Zf3-imSJubZS2
OnGzcX_80G
}

sprite $CloudStorageParticipant [50x50/4z] {
pTHL0iGW00FHPEv_vtNtsMh-MdWuPFtXJMe1e05ueG5eW1TeGBNW2RXE2h8JaAHQW20AK2qu0qdwvVmy5_D1j2_A-IJ0YTVJxDEFXp0yVbJn8dgj8lj84YNq
kMeioJ6r8F4Y6iIB220ctu7lRcf1uaK44CAGMD5OaZUfg3zfjW
}


!define CloudStorage(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudStorage, resource)
!define CloudStorage(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudStorage, resource)
!define CloudStorage_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudStorage, new_resource)
!define CloudStorage_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudStorage, new_resource)
!define CloudStorage_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudStorage, modified_resource)
!define CloudStorage_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudStorage, modified_resource)
!define CloudStorage_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudStorage, deleted_resource)
!define CloudStorage_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudStorage, deleted_resource)
!define CloudStorageParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudStorageParticipant, CloudStorageParticipant)
!define CloudStorageParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudStorageParticipant, CloudStorageParticipant)
