sprite $CloudFilestore [70x70/4z] {
pTC7RaCn40DHKlS_TD2OdjN6mvH1TNkY1NobUfxJfdFD44aR1A_nsSMc9BCfYKr9PbCIcvBCfYGs9PaXQL0euufo4c5SKKuYZ2lAUQmxulSzf6Ypzrj8KV7y
jGFoS8RtZ_tYetG_q8Eo7pFysPNYJ655P_boAvVtadHsYe2olTz_fRYWIEeenahUBYY6IjwlA4QAKaSnK0P_rtl534aTnGn97SKCIHt534b0GOnQ2cVKKAm6
euPYDHWr54rr53CaTHHl4Jx6kcQmXFK4
}

sprite $CloudFilestoreParticipant [50x50/4z] {
nT95aWD15CHGPTx_pZDc_Ere6RMjUCMyLZgdGHlckfm6CuaMhIJHefKaMhIIH8jMadeXo01oqJh1iUMXhXQPnQCcm6t38kh30LGLBJgV8jqtdcGKPDyaEefZ
lnA05r4202yY1FkyIDV6CIzY0NWH2q08GV324hom12yimOfW2KZ2OhbjsD8_
}


!define CloudFilestore(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudFilestore, resource)
!define CloudFilestore(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudFilestore, resource)
!define CloudFilestoreParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudFilestoreParticipant, CloudFilestoreParticipant)
!define CloudFilestoreParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudFilestoreParticipant, CloudFilestoreParticipant)
