sprite $PersistentDisk [70x70/4z] {
xTS5RaD140JHxhh_dSE2q6ZihN1AR7Zwk91b_nMOMo1iKX2QiO9mC6nJ4AeeJ8XmC0NXO41WgYXSce9GHM50JWwc81mC24mLPVX-_pEkLgeeJ5_kbUQfdYXC
tt7fXC1dAZF3h2oUy2OzLqWGbBwh561GblaAp5KvXcoLtiSxfKjblaSHb2JTATRBCYivL38eVL7k6wSsPQnB3vJASq2gp6fnb71TCPJ6O68iWogjwuI3aTQx
1XD3QGmcnjQcqbvDE9XCEKeK96LJ8p0PsZhD7-WM
}

GCPEntityColoring(PersistentDisk)
!define PersistentDisk(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, PersistentDisk, PersistentDisk)
!define PersistentDisk(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, PersistentDisk, PersistentDisk)
