' GCP-C4-PlantUML
' https://github.com/gamma-data/GCP-C4-PlantUML

' Colors
' ##################################
!define GCP_COLOR #0072C6
!define GCP_BG_COLOR #FFFFFF
!define GCP_BORDER_COLOR #3C7FC0
!define GCP_SYMBOL_COLOR GCP_COLOR

!define YELLOW #FFFF00
!define GREEN #00FF00
!define RED #FF0000
!define GCP_MODIFIED_SYMBOL_COLOR YELLOW
!define GCP_NEW_SYMBOL_COLOR GREEN
!define GCP_DELETED_SYMBOL_COLOR RED


' Styling
' ##################################

!define TECHN_FONT_SIZE 12

skinparam defaultTextAlignment center

skinparam wrapWidth 200
skinparam maxMessageSize 150

skinparam rectangle {
    StereotypeFontSize 12
}

skinparam Arrow {
    Color #666666
    FontColor #666666
    FontSize 12
}

skinparam rectangle<< resource >> {
    BackgroundColor GCP_BG_COLOR
    BorderColor GCP_BORDER_COLOR
}

skinparam rectangle<< modified_resource >> {
    BackgroundColor GCP_BG_COLOR
    BorderColor GCP_MODIFIED_SYMBOL_COLOR
}

skinparam rectangle<< new_resource >> {
    BackgroundColor GCP_BG_COLOR
    BorderColor GCP_NEW_SYMBOL_COLOR
}

skinparam rectangle<< deleted_resource >> {
    BackgroundColor GCP_BG_COLOR
    BorderColor GCP_DELETED_SYMBOL_COLOR
}

skinparam participant {
    BackgroundColor GCP_BG_COLOR
    BorderColor GCP_BORDER_COLOR
}

' Layout
' ##################################

!definelong LAYOUT_AS_SKETCH
skinparam backgroundColor #EEEBDC
skinparam handwritten true
skinparam defaultFontName "Comic Sans MS"
center footer <font color=red>Warning:</font> Created for discussion, needs to be validated
!enddefinelong

!define LAYOUT_TOP_DOWN top to bottom direction
!define LAYOUT_LEFT_RIGHT left to right direction

' Elements
' ##################################

!definelong GCPEntity(e_alias, e_label, e_techn, e_color, e_sprite, e_stereo)
rectangle "==e_label\n<color:e_color><$e_sprite></color>\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//" <<e_stereo>> as e_alias
!enddefinelong

!definelong GCPEntity(e_alias, e_label, e_techn, e_descr, e_color, e_sprite, e_stereo)
rectangle "==e_label\n<color:e_color><$e_sprite></color>\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//\n\n e_descr" <<e_stereo>> as e_alias
!enddefinelong

!definelong GCPParticipant(p_alias, p_label, p_techn, p_color, p_sprite, p_stereo)
participant "p_label\n<size:TECHN_FONT_SIZE>[p_techn]</size>" as p_alias << ($p_sprite, p_color) p_stereo>>
!enddefinelong

!definelong GCPParticipant(p_alias, p_label, p_techn, p_descr, p_color, p_sprite, p_stereo)
participant "p_label\n<size:TECHN_FONT_SIZE>[p_techn]</size>\n\n p_descr" as p_alias << ($p_sprite, p_color) p_stereo>>
!enddefinelong