sprite $Stackdriver [70x70/4z] {
xPV7bSDG30C1z5_qNjU9VwY7YmCA60-J9Gdc5-SK00b91HBlozdBXAO2YIkKJ922Z9E2J5B0k4B9DXL8NA44GVOoJWeokPQZ2f8zgVXHrWTCY8gKntYhyhog
WyeZP9On6k7qUxoULvGiMkkXUAuohGrLcITXoKnbnF0fppAmjVk7y6tco-MnZgUxTybZyBRC55TcX6NcvJMVzR3gkxtpzXpvJNEPgRLGHg1wrk11fVSCuDCU
85ZcsYFsBW2YN8hLmAZn6kJIUrr1flI-sy2eGR4Q63K-RLpwLYl8Q4g7eW84rsGLC08n4Fdu_04
}

sprite $StackdriverParticipant [50x50/4z] {
pTH75iDG349HOF-BpYnLJyUaCxNlxvB-Fu4O0OT0INgHb2Hl5wb1N8iCe9d4IJb9KXBJK2WOQ2PPXCRDCu3Xw0WTQoHUffW50siaOG5dpm1knIpw9m7YoAgy
20z71OTLdDL-vVKL0j1IDV3i-hShCu5lsmaVAbjV4W35moc9sXRd5_kkt0Af5of08HgYLbWj4SJq_xTp0W
}


GCPEntityColoring(Stackdriver)
!define Stackdriver(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Stackdriver, Stackdriver)
!define Stackdriver(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Stackdriver, Stackdriver)
!define StackdriverParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, StackdriverParticipant, StackdriverParticipant)
!define StackdriverParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, StackdriverParticipant, StackdriverParticipant)
