sprite $TrafficDirector [70x70/4z] {
hPW5ZWLH20Gfxd_dzVraXFxDX8wFLEgvn2L0YW3nFkJRu41CZ8OiODBCM6KkatQqoe9C3g9K5cHo5ANY1rz5aMqLb22kYYwcgwAh75T5ozWgCQePyOqlmpCA
6g9hjy8wXTGKzSaoXNnEILeAp2bSdzkKmd3pT439WjmMyqZHCbsVng8qhoaE9eLIkSKK9LAacoUBvSmpq3wTKTeSAS4p2aTAQ8h652NQzGbTzqTAa8Xbow2e
6O33GpqpHClXy4nJij7vU-vI4aN1erGV4WkEHw4Vlame_U1TcBtNrgDuJXbi3FKQN7bAyNUfUdFYoiWjcos3Kl5bK2f-pKWLNqQf-39InPVHAlidcvXHjavy
2p9R9-45cQqRWWMPfPkJ1GoBDqewo2Gta4y
}

GCPEntityColoring(TrafficDirector)
!define TrafficDirector(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, TrafficDirector, TrafficDirector)
!define TrafficDirector(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, TrafficDirector, TrafficDirector)
