sprite $TransferAppliance [70x70/4z] {
xPX7aWCW40Cb_V_FkyvnYEwRtMUgImmPJVB36Q4ncG6HnCFk064o2oA94KiGIJkC4o1C0cYCMB8A8eaHIn19N9GM29C06YEMx898OiGIH78FuuzMoZ2AD3F9
1v98oRobxkh9uh4bTHITcTv1N9TsTJfB0R2uFR6Uqeban99CMTpiXXUoC7MHaJ5IipHBkuDNvwxBzksvMvkyjAXdBHfPIjoOOCXU9sSVGsS040Ow6mcD28j5
Q4HSWmpTwu0mq7sNq8YmM8H6nDF6q5iD20EzOGcDY6Uv1MY8Jm_h2_W7
}

GCPEntityColoring(TransferAppliance)
!define TransferAppliance(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, TransferAppliance, TransferAppliance)
!define TransferAppliance(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, TransferAppliance, TransferAppliance)
