sprite $CloudCDN [70x70/4z] {
xTP7Sa0n309GuFvtJkyECffXbx3z-c_SROJv3tLBW2X91H6ltIaqHcagY5XHL45yOwXDV5CA32kAjgaWuaAXx-e60PWsPYvas1YFB1WE28y2fqo8KcPeB-SH
PgIyrIOZ8rl1wwBXTGDz-SBhqfCBbSGXFbxnKumlaP_m6Vccq3C4Q953iGnW4EbGF4FObfoAPnnYb9HvgtAAVfrMvctnYE1QSoeU4MYOK_48WNIzU4HsJPzh
ro06tmSDPdE-y7hF1cTTSCtoUkv6jwnLtdxERaVEUsegYQ-riI9bKiHNCVXic7nvvo_C0U7cIRPvP5BRbDwx3GODXMWmSE6kAON6m8SD1EWeA21nduW20vlS
8Vv07W4
}

GCPEntityColoring(CloudCDN)
!define CloudCDN(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudCDN, CloudCDN)
!define CloudCDN(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudCDN, CloudCDN)
