sprite $CloudFirewallRules [70x70/4] {
0000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000026AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA220000000000000000
0000000000000006ggggggggggggggggggggggggggggggggggggggQ200000000000000
00000000000002ggggggggggggggggggggggggggggggggggggggggggQ1000000000000
000000000001QgggggggggggggggggggggggggggggggggggggggggggggA00000000000
0000000000Aggggggggggggggggggggggggggggggggggggggggggggggggg6000000000
000000006ggggggggggggggggggggggggggggggggggggggggggggggggggggQ20000000
0000002QgggggggggggggbWWWWWWWWWWWWgggWWWWWWWWWWWWggggggggggggggA100000
00001AgggggggggggggggQAAAAAAAAAAAAgggAAAAAAAAAAAAgggggggggggggggg60000
000AgggggggggggggggggbWWWWgggWWWWWWWWWWWWbggWWWWWgggggggggggggggggg200
06gggggggggggggggggggQAAAAgggAAAAAAAAAAAAQggAAAAAgggggggggggggggggggQ1
AggggggggggggggggggggbWWWWWWWWWWWWgggWWWWWWWWWWWWggggggggggggggggggggg
GfgggggggggggggggggggQAAAAAAAAAAAAgggAAAAAAAAAAAAggggggggggggggggggggf
00aggggggggggggggggggbWWWWgggWWWWWWWWWWWWbggWWWWWgggggggggggggggggggW0
0000eggggggggggggggggQAAAAgggAAAAAAAAAAAAQggAAAAAggggggggggggggggga000
00000GfggggggggggggggbWWWWWWWWWWWWgggWWWWWWWWWWWWgggggggggggggggeG0000
0000000WgggggggggggggQAAAAAAAAAAAAgggAAAAAAAAAAAAgggggggggggggfW000000
000000000aggggggggggggggggggggggggggggggggggggggggggggggggggga00000000
0000000000Geggggggggggggggggggggggggggggggggggggggggggggggge0000000000
000000000000WfgggggggggggggggggggggggggggggggggggggggggggfG00000000000
00000000000000agggggggggggggggggggggggggggggggggggggggggW0000000000000
0000000000000000afgggggggggggggggggggggggggggggggggggea000000000000000
0000000000000000000GWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWG000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000
}

GCPEntityColoring(CloudFirewallRules)
!define CloudFirewallRules(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudFirewallRules, CloudFirewallRules)
!define CloudFirewallRules(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudFirewallRules, CloudFirewallRules)
