sprite $CloudExternalIPAddresses [70x70/4z] {
xTOvUiGm5CDWaFU_S_PTZgnOI3M3MjzlTduiTYyzY_Ewae8qJ4ihZEbg2j8eIcU8C2QjCAOLc2XA_vg2D8fI1Hd7f1N6j08JHLb_F65wMSb4-RaJW2JJf_rH
3fMsixVPKJfCMLT6feVAuVTSPMIwhGIohnGgA9ae6_sxCg6ZA3XA12KWA42s5G0SXKq5GmblRIcybr4XGyTApduFOxCfaCiANtCKUYqC9HWCnXaKwQuJnaZt
hi5WAC5W-AqOKy2O0Z4GS1GKX7Ib8300kqwuWHu1
}

sprite $CloudExternalIPAddressesParticipant [50x50/4z] {
pTI5SSHG0CHGxVRVSnW_pIWvqg7XcMqUlswA1MqrQ2yZMabwSL4D6Yqw0hcIj78bhIJHuZpzFAhvR3av-r7GVdxFwwqG1SWWnesUHPKez88Y7_LtcOLh5D0n
RY6G0l029R0Yl2N4V0k6iHK0B_oJ0I_GW5G_UEqg81Q05mWWX25O4InXKxgEM_SC
}


!define CloudExternalIPAddresses(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudExternalIPAddresses, resource)
!define CloudExternalIPAddresses(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudExternalIPAddresses, resource)
!define CloudExternalIPAddressesParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudExternalIPAddressesParticipant, CloudExternalIPAddressesParticipant)
!define CloudExternalIPAddressesParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudExternalIPAddressesParticipant, CloudExternalIPAddressesParticipant)
