sprite $CloudNetwork [70x70/4z] {
xPT9SWH130A1_p_QvzaePfpUpLKL6QdUfDQO_pYd390iGI3niHr09ciGI8nGqY20Z1D09W4mHYXvDWWaHYX18BSoJW2Pl9PPfHPNbQ6yG7hTCsNiAPjBbt7U
WzdkikHLjogdONPASiHae7GRIvue7VEef9k2I_lM0qZ1VExWUtgI-_5JxQiK5ptn3XQASpU-Tslzw71z2kIRsrXEbcAZx9_3cT8nFbA0JrrY4PXb6XqF69u1
yiiTyREnJvnIGtO6Yy28M8CCxNM03BJl4XWH58l0YFYrCVIl1iYeXQ48WCmzMG16Gpo8_Fgy0G
}

GCPEntityColoring(CloudNetwork)
!define CloudNetwork(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudNetwork, CloudNetwork)
!define CloudNetwork(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudNetwork, CloudNetwork)
