sprite $CloudNAT [70x70/4z] {
xPS7hWGX34Dvll-TVzq-X9YHrSVR5_JaK9FXwHAe4VGG6QA7130orLa9c96jX1K95-9ZyXIa04QRggm4p6XR2IiI2OY4Hs5DnuICBKpLgSFqLkuOsyoa6N1Y
ggqyOZ4mD91VWUoOfastPZicrZxnp6YYLxnZfbvm7B_MPjIe2Qasow7N_HlsRkFEdb0AJBLMUEZk6A2QqdcKxtli_hPO6L6A7z5qU2EZE_zxSwOZgowp0oAx
CNao35QdbEmZise2zLOYftVa9idVQkCaHEvjhqJIi9bDwOG8PMG1CwbCDM0cbC4dC84YArGW4QduKjLdm4oeAWzW69t0XFIwz0q
}

GCPEntityColoring(CloudNAT)
!define CloudNAT(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudNAT, CloudNAT)
!define CloudNAT(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudNAT, CloudNAT)
