sprite $CloudFirewallRules [70x70/4z] {
xTYrbKD10CLGFVLVzCPc66LhnJxNdmTuir_pLRpETqeGz_9qWeFntHB49OhFaE1Wfi71QC0iKVoq1769Oe8uhfe61wC1iqHvShvNltt2-BMoHF7mqbx_upof
E1Jr4R8xrsCAGAfSCnuhWtaU63JiEdXsGsM9WaMikOw10Ynv0sWKadSQZne5G_79N3m6i6HKer7mkoYKKJ0Kqw15yxhWOABvRi5GAADWA9OsYzPgmS54QzY2
eLYMZu0fDZt6F-WF
}

sprite $CloudFirewallRulesParticipant [50x50/4z] {
pTJ50KCn40DHQVhlESmy-QYpdtatwmzlKWi03S0B3K03l403gWLFm2rIa8k09DNYnLuXvxmW_2pgJW6W0JmTkuyRIl8aK8846IyeyFFj7gD5teh-9lpHsnPw
3hHz1Fuz4YNqlseioJ7L5HKXR6VmmfBO5jU1VJUr8F4Y0WXXIAneBCcRL8oVD5i
}


!define CloudFirewallRules(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudFirewallRules, resource)
!define CloudFirewallRules(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudFirewallRules, resource)
!define CloudFirewallRules_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudFirewallRules, new_resource)
!define CloudFirewallRules_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudFirewallRules, new_resource)
!define CloudFirewallRules_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudFirewallRules, modified_resource)
!define CloudFirewallRules_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudFirewallRules, modified_resource)
!define CloudFirewallRules_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudFirewallRules, deleted_resource)
!define CloudFirewallRules_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudFirewallRules, deleted_resource)
!define CloudFirewallRulesParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudFirewallRulesParticipant, CloudFirewallRulesParticipant)
!define CloudFirewallRulesParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudFirewallRulesParticipant, CloudFirewallRulesParticipant)
