sprite $CloudLoadBalancing [70x70/4z] {
xTW5SWH1049HuFvtZdj2jVtuKh8wRwIzDPbBd54qJcQ28F7mTe2BoMmG94QK84Y_62V0nIG0OqJ9QX0aHfGWI5mUxU75901ZH4a0fZ-wuRyG9UNdeWp_vXCb
zTUkT2PVhNGcWqWUDoUVAv42A0OKe6ic5NVbtHrrHOnYG77f5Ip9p-_yyCvsEQNxitrk1dx-hloRKNIeY52iXnmfUnMxTqC9qE2eLdkW08m8nI8O4TCWG_Cw
u6AW-Ix1Y50iWX6nj36qLWCk1bh34eo8PRa5CCIcX_KFSWq
}

sprite $CloudLoadBalancingParticipant [50x50/4z] {
pTF7OGDH30DHOFelsZVR4fH6cPj9liq_tn-SYLe0Q03F4I09JnTeGBLWWBj8GLu49AaM8CcPzDQe5coI5Lki5bmIPQkSYNC5BwZ_HRN8YeF2KqJcrRRG_csc
OHB9uMORb8WLpQRQzcYpVr3rY8eNqI1UH8CK_O_QIoIr8F4Y0WXXIAneBCcPgEX_QVm
}


!define CloudLoadBalancing(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudLoadBalancing, resource)
!define CloudLoadBalancing(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudLoadBalancing, resource)
!define CloudLoadBalancingParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudLoadBalancingParticipant, CloudLoadBalancingParticipant)
!define CloudLoadBalancingParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudLoadBalancingParticipant, CloudLoadBalancingParticipant)
