sprite $CloudNAT [70x70/16z] {
vPS5jWCn24KV4c3_6_vQRnZ8oHpjhRTZl1ihFW6MGnWDrAF05HKM3Gp7Z6WnS0H54ohhsQr9eeqWnQEDvv9ZWKmtUIpWL5ZUiSsn21UMUrZJyhfjZsMyiDn4
UvO7UsMxjknL8neTorQsHUvOjgeTsR5bK_NBLjgqxVFqxLAvjsphD5Q0H3q4u8vjcfRxdx-4Kz4vA8tM0IOGCtiCW6lRd8PcjvFLjfDMA-BtohMoBL7XrTWZ
yqjv-Gx0TNkRdqRdSOsNmc_lnjIs9utQ_ChrYjtT2H2V93EhaenmnqB-doxGh6Mi7wMuc5v5CzSoJPSMqqqQNMRQYmQrr-fWP_G0q2cz4Nh6o03uqIWL15Xd
Jf9in5IDq6h4h4RlooJG6xsd9pCTVjceEPFaXVlAh0RAjw65zPIci_tIsYvRUQmjv6Lx5RI_8ijjryYfAzN2TZFQqdPjUJDW9CY6vIBWolAMRKREsB1yzZzX
w8BbtPeC5UeToJKin-0J-0O
}

GCPEntityColoring(CloudNAT)
!define CloudNAT(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudNAT, CloudNAT)
!define CloudNAT(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudNAT, CloudNAT)
