sprite $CloudRoutes [70x70/4z] {
xPOtTiDG40CnkF-XNIbhFzPywEof98OXzcSj-GSdKCGRAX8Jooc4yPQAn5GihaZcCDY5C7P1GyNYtrAHc8h5GN8r3Bx2XIX43Sv8oU85IXfl-FeWimK0lbd4
76Rml___gY7TODKHGnJpUaDAcj1YGRAqo4QlXCxxNkvJrqmI8t6UQTZFfOLHFMeU3vs-62ViVHhAWQ09j3GiDCH7TRp5SnZD6d78yLhJN1kdE-AkIUFbMnW0
wKK3QD8ivf7r2eD5vpbDsYugwmlB5VCS9TXPRHTSEIgVDYGkxqSNzaOAMwoS9F8bK4EZnZ68qhck4APqtcrerB2WXaOJDA98ZIWI3OdKiQWWMTU42Xf5iWVz
0Nu
}

GCPEntityColoring(CloudRoutes)
!define CloudRoutes(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudRoutes, CloudRoutes)
!define CloudRoutes(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudRoutes, CloudRoutes)
