sprite $CloudRouter [70x70/4z] {
xTOnRaCn38FXdxh_eJithcWQuDPmZV113vPY4-ORpIq1CaagoEZwEOLc9aq56LMKSKYX6SrBzbOAZ2hAlAQ2Z2hAl23apMX7KDoCASmP-J829QXIm5Z4Cxeh
oJUdY6U4_nqYnhI2_ZmZxSmsQgSYNXLEHJ0Riq_iXwAjMA1LGRyKiIa3xcYMyJgRiGfAPzGgw42yujSKhyWhuUwIxhfNP9HiUVquyZ5rRbxGfXmRi2blUpHE
mSnqjDEhecl9ETNfbUNBrFZVXSPbaryJPrftOyvCXlYw_05JUR-WUOzAxxf2CwNtReEXeOW6mnOrMe56Aw060Xs52e8YH1GOJ597_8Fy
}

sprite $CloudRouterParticipant [50x50/4z] {
pPO5jiD030Cbt__E7ykhSUgo7WP6VZ5bzVaga15W8S1w356z07WeKMEWF2Og09CW3evjaFYqHPoV4S6F664l-lW04096zh-NxIglY5DM3rRMIYnnJmd7vul9
aJ0uOlAS4k0cguQKSKqL2NMLkvvekqBYNCKMRkj1ZiAQfydQQaGvD-zWrEX-0_GZvT7OCi2xnDFrim78jItVkNVbAI3D2Gs1EV7ulxCVT6RW5ElL-WO
}


!define CloudRouter(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudRouter, resource)
!define CloudRouter(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudRouter, resource)
!define CloudRouterParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudRouterParticipant, CloudRouterParticipant)
!define CloudRouterParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudRouterParticipant, CloudRouterParticipant)
