sprite $CloudCDN [70x70/4z] {
xTP7Sa0n309GuFvtJkyECffXbx3z-c_SROJv3tLBW2X91H6ltIaqHcagY5XHL45yOwXDV5CA32kAjgaWuaAXx-e60PWsPYvas1YFB1WE28y2fqo8KcPeB-SH
PgIyrIOZ8rl1wwBXTGDz-SBhqfCBbSGXFbxnKumlaP_m6Vccq3C4Q953iGnW4EbGF4FObfoAPnnYb9HvgtAAVfrMvctnYE1QSoeU4MYOK_48WNIzU4HsJPzh
ro06tmSDPdE-y7hF1cTTSCtoUkv6jwnLtdxERaVEUsegYQ-riI9bKiHNCVXic7nvvo_C0U7cIRPvP5BRbDwx3GODXMWmSE6kAON6m8SD1EWeA21nduW20vlS
8Vv07W4
}

sprite $CloudCDNParticipant [50x50/4z] {
pTK5iW9H44FH9FlVynTqv5QeneFJTKQUwlkJS5m1fmBESqHw03nTP0pYiSWje7uIqm7BIR3OYQ7a4s61brG8dTqv4Bfv5ZxMeS8WNdm2SKfGxFvnT0xSFeA5
s1C9m480CGoDXG02PrW8kba1kGe0wVS1W6vz8GZq_k0EKoOH2vUPMySkLOunpuys2R4hiT180uErf9CEvEcQgFcwAq-1D1SQWhbu_kviJOd4SJXwTtu1
}


GCPEntityColoring(CloudCDN)
!define CloudCDN(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudCDN, CloudCDN)
!define CloudCDN(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudCDN, CloudCDN)
