sprite $CloudArmor [70x70/4z] {
xTR12WCX48FXPDx_eNiJ9FxMWRcrEJho6Q7TNJtc7zUtF23raX6atBzElqozPWGfZoWrWd0PLoTSPO3nY5BTD11VHg-AhxTzG_muNp6VLBSjU_0gEtXd34Qi
N9MZ0J8ofq5b3enlYaEW6I0520nN6JSL-47qbMHuus7QLxIkQuCIXu6YjGqLnrfsMHeg9HKeUvMxObOaoLw_28UIIMKTxrMbfLZoZcWxeZ8-AWA4596o8xQl
YYiIo5e1nQV57TbSVFpwH6j3DeMxvt8WQmaK7PS3CV_-kSoEcD-sbhXC8FSgF4g4g-3CZ6GLBkD0p0YVOK18uQg-_x9IuH-Je8aL3Esn2ActBypUjnH_7RuC
iqp6E1dwtfrWDA5O4umexbKPA2EE9n1fHj44ylv1CC08y-vOFv0F
}

GCPEntityColoring(CloudArmor)
!define CloudArmor(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudArmor, CloudArmor)
!define CloudArmor(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudArmor, CloudArmor)
