sprite $CloudRouter [70x70/16z] {
xTPLUYH130DW3LfBxVkVTiDiUTJVE1mzL_t5a6P-mjDnZ0664mpT321Z2WUGCOKZ22KomN22uJifD91XPKSP7m7sBXCDKZ12QH5WfnaV0VRdA831-8XcufG2
E8oDz8nMTl6KuatsMc6b80fb3og6jOANoW6riZGAuh5oWq3D3AM2UA8S81M-L3Qu3nzoWm2IqWgYGDOhY08nbQ86pbB8Wh5cjow_LX75UqNlbsUxJaz9jtTV
d81EMUnpHA4qPvg54gKIgPWzAwM_fUGCEvjjoJLCoAxq2hV6jZVUers12CLXma6I_Q1uxdE_Mu4a6oQe4bamx_EnonbbWiaPPOB92ILLPfHV4qZcZBBuI1SR
wJEZv03YCVaDSW4
}

GCPEntityColoring(CloudRouter)
!define CloudRouter(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudRouter, CloudRouter)
!define CloudRouter(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudRouter, CloudRouter)
