sprite $PartnerInterconnect [70x70/4z] {
xTWtMWKn00DXZUv_Q2f2jIliwK3b2__dd3BcF_Gj0z8b2b9UgoCKfciKf2XAdn2XCBH2OLg1GL7wsoX8KPGEo4bXQ8N2j0A3eXmFXk7RGK5HEZPjagctkL4w
56LGEY3dIhxoGtaP5RrMIBXNcbHG49G7u47vfcG5HN7Q9GWAYQ0auLfnvf6pCXWAMPXve7AX8Ey1uLXnzaPdjpSKOZ0nZa58vpgXCD9vrs1YACHWObnjaEvg
Gc6aEwp1nBYM4u4n7Zt87yW7
}

GCPEntityColoring(PartnerInterconnect)
!define PartnerInterconnect(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, PartnerInterconnect, PartnerInterconnect)
!define PartnerInterconnect(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, PartnerInterconnect, PartnerInterconnect)
