sprite $PremiumNetworkTier [70x70/4z] {
xTOtOiH034DHVDp_q6wSAGvf2PqNdSAy0JTAoxo2fsYEDuaWPXmdKCRRH10JKHn1-ZBOWJ9sW26Y-A-982QYE8BKCjY1CkDcB1XkxhIwONREL_dHahOp9wKk
ec46f9uknhdchH_Fo_FzcbrnUgHhtjYkwJjsIFygsfRg9Vfvgg7hdHVpw2iq_HcL-jcKy106fCjSPKQe2bSAvrLreFdpNPg9bSBn9eegvc-cwbPu2AjljPz6
2KO91IKOVOH45IbHHU894YYZ1AE4WXAC4ez1X9xh0cL2pxi9HWa59HXr8L55IbIHI21IHb40MS-40ep6p0xw1ta3
}

sprite $PremiumNetworkTierParticipant [50x50/4z] {
pT45aWD134FHBz__piiGTwokKLW5mMSQNZzb8Wjy70X9Bgf2KZSN5ODIB2e6lOdgIBOjDDQnBMnpqs9t4lzbstLOle7rSxKCODfN2z4Ux6VGUBRrcx5UNnpK
n0puYSuAgOiLr3PgBIp03jK_7X2jWtalx9FfjIeBAI4L8YLyHoc0N103Sa40WkK5OHDwb0B81G48H498XKW99gevF3hl
}


GCPEntityColoring(PremiumNetworkTier)
!define PremiumNetworkTier(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, PremiumNetworkTier, PremiumNetworkTier)
!define PremiumNetworkTier(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, PremiumNetworkTier, PremiumNetworkTier)
