sprite $StandardNetworkTier [70x70/4z] {
xTO5SWH134DHVT__pk7bLjjJeyAimh2lvM4DymxLHNrgaWXIjEC4ojGq4QI8A1L1V1dgI7oL04D4gQE984L4gGXID9jsc7cLxHA3Ah-uVh-WNd5JNxiWjOoj
-qI-XftoEmHrYziwkof-PLFcTH7MUyRyrbJXiZNbbLTcDOrbg9bocV7OtMcrjMvhK7qV92pCUk05lQp2qqwaKz1kHbtI73Db-thc-EOUAimKjgygsO5y5rxA
YUrPo4fPiLkbU4KAk_DzOB9BL6UZ1AE4WXACBY5HHKfKaJY31CeemIYXe0IZn6CGeUUwG9dGysw2KK912KOk9Af8YIeI2KJAA0eWuvbGW97Dt47_89y
}

sprite $StandardNetworkTierParticipant [50x50/4z] {
pTC5hW8154FHs-v_pzy5Q1fIl35aphDaUFsuH1NqpC2-ZR17ufiBpy2QXGDiJMIFJPn1ZjGMO0EsQ29AwPS5IQ33qb2MZv7wzm38EbcB93fgQdDAOfEe1-0Q
4YI1Sq9yfIn_kiLNXXSWZvZXKAW9L8J_SYn4F1P2j0C1ti9AM8LO2T_H2c0G8s4LOYKSHciBM5k0LW2xO023M0Yh42kXf9sOH-ST
}


!define StandardNetworkTier(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, StandardNetworkTier, resource)
!define StandardNetworkTier(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, StandardNetworkTier, resource)
!define StandardNetworkTier_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, StandardNetworkTier, new_resource)
!define StandardNetworkTier_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, StandardNetworkTier, new_resource)
!define StandardNetworkTier_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, StandardNetworkTier, modified_resource)
!define StandardNetworkTier_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, StandardNetworkTier, modified_resource)
!define StandardNetworkTier_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, StandardNetworkTier, deleted_resource)
!define StandardNetworkTier_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, StandardNetworkTier, deleted_resource)
!define StandardNetworkTierParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, StandardNetworkTierParticipant, StandardNetworkTierParticipant)
!define StandardNetworkTierParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, StandardNetworkTierParticipant, StandardNetworkTierParticipant)
