sprite $VirtualPrivateCloud [70x70/4z] {
xPW7QWH030Cz-l-ZGqqpJjOmrq_KbM3OtkfGRv7_T039YHH8s3TdNvcSIe44XH85CbU6HAXC8c1GADbAWGI54WNIAqCYL2OHC2YKAQGRCoPZDXYVGg0CoPx2
tBMRBMW8bfGCla_fHjTWBocqhcqTtuskghycToiFGg4aTqH1ePH3GQ3GejqkzPcYh80IACREO53uJ8ozhX3sNUiCAFQK3caPdngCJpcdlK6X34mPro2aUvrG
6Uc-Qs3Ae506feod3T9RJQYCz8OrC6Kyooa1OtnwK2-W3m
}

GCPEntityColoring(VirtualPrivateCloud)
!define VirtualPrivateCloud(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, VirtualPrivateCloud, VirtualPrivateCloud)
!define VirtualPrivateCloud(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, VirtualPrivateCloud, VirtualPrivateCloud)
