sprite $CloudServiceMesh [70x70/4z] {
hPW73iH020CP___HfxgfXkp9LacVM885ade8r0fg5Xf50Y8nGm8OVTHa9M16dzLR2PZHXZeh0JFQahSICADDEIi1CzfMmeh45ok0ER1cU4BEfyqjivKpd9em
_GqduaX16nIBmSQH1z5IQEB8QQ_7q2K43BSiY4kKvotWC3pFtp7dHtILXJmmboSmmJIKTT0yiD2UilOPN-iZl5v3bUGZtgKr2w9BsjJR0tws4EUiGtukARxa
4aD-WbeCZyEHuhD6GrNr5wwF_KLX2qEPqnSCA-oEWeaqkaGQuIFTLzowr1Uwwikm0XRJOHZNz8BCHM2i34L3eSnPMvVyM-UAILjAN7i5RWayLk-vaqXTyayJ
q5vNcpjizHrswTzklpLvu6wAJ44V9p8D4rbkEinFggLjfIRuW9dKbqt0JEgBBs0czIKSC9FwGn0m4_fp4i0G_gFanRkwlri_
}

GCPEntityColoring(CloudServiceMesh)
!define CloudServiceMesh(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudServiceMesh, CloudServiceMesh)
!define CloudServiceMesh(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudServiceMesh, CloudServiceMesh)
