sprite $CloudAPIs [70x70/4z] {
xPSvTiDG30C1tF_GgQWgub3leKlWtOP7NAI_wAX_EIInSb454cCwXM1oLGKILoYfGEAbj8LWaWB65Kg-gWA9lr1q3sQrdeFnUhn3CEIxOqmkf939ZE604oyM
toXZNIpSvJaYTzjymfbFlOmMb0COW83ZHZbQzhzAydJg3MZ914aG8p64CHP36CEHB1Y2U0gRqNpu_JGrOnWISJGCYOmOXbWAOG0oBi00v7oHk70v8eGeVfxU
JHPXdZ0spyYG3Soo4Coq42oNgT6vpchiCLC0SuDmskRICiPKsbktAHGE9Ww40i60IklT1aODYjN0gB6rSMclLWX6cpeK5I3ddAm2HYZcM7z0Fm
}

sprite $CloudAPIsParticipant [50x50/4z] {
pTQ55G8m30N0_Eo_CwwbXrlmygvkzV_HY10u21nl40Oc_NRH0ev8E6w1N2yaFSOyhLm4id4HI7OHcpGKpJfjtdkCM6m_qCFesNXGWdz2SP6IawoI3782QllH
1vfH0BH814Z6tjv-dDLWQ6k106m5242NY46vITCe4WAlM9Kz9U7SrHACrWVNOCfhq8I0BIcqmiHWRBmZB-wxbKT1rUEY7WIFY_UVpddJdS5TND-E9G
}


!define CloudAPIs(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudAPIs, resource)
!define CloudAPIs(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudAPIs, resource)
!define CloudAPIs_New(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudAPIs, new_resource)
!define CloudAPIs_New(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudAPIs, new_resource)
!define CloudAPIs_Modified(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudAPIs, modified_resource)
!define CloudAPIs_Modified(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudAPIs, modified_resource)
!define CloudAPIs_Deleted(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudAPIs, deleted_resource)
!define CloudAPIs_Deleted(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudAPIs, deleted_resource)
!define CloudAPIsParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, CloudAPIsParticipant, CloudAPIsParticipant)
!define CloudAPIsParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, CloudAPIsParticipant, CloudAPIsParticipant)
