sprite $CloudServiceMesh [70x70/16z] {
pPW5hjr034KzO2ZlVxM5ECajs9hCazl-8_ZuZguX-ELtx05VLfWLQEmXvPPz2QYnp2t9VfZFje7cKGh2lBCAZLLOn3RHE4f16BKAZLLOx2KUM9JPRcH6tLzB
c8YwcZE8YACnhIoDlZDX90e6i98e_M0W2b5IqzhIxQ0_iLX4fxkaUNpRB69XKTVmrPMcgIMNt1b4N9QHMLGmu9Dv_qqJIvH0VjMCoz7kxq5eaMitqEEE7GgA
ow8WZ3QN13i4SWjZJarD4JEqG8AAK5BtxxGDH0d61GkOztgCKzUE8MaBehZ50bJQ3uthv4p7ThH8r9w0fc8WV8JpW3ieEOmYDoNeCLPseEER6bWmhJtqR0P3
yq9RshoEQC-bvYFQSKWdWiR4z_VGu9XUB0pxFAwUgdg7hhdDG98U0N8tuoe5V_cTnT5uD0FzuDrZMh34c8t6blmi5Uv9VfQAmx1XPo4nYQ8ipjwOTUVR8w4a
lm72-Ww4sxuWZMjOudFILEBeuWex5bVOWgiza8LbBYnv6Dgy2uhltjbRWPBc-iRP_aGc6vmphmTCUm4jkcikq4Y9fUJvQ9POIfuRFvTOQfwdQot__pt3Mt__
0Weaq6nAlW4
}

GCPEntityColoring(CloudServiceMesh)
!define CloudServiceMesh(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, CloudServiceMesh, CloudServiceMesh)
!define CloudServiceMesh(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, CloudServiceMesh, CloudServiceMesh)
