sprite $ErrorReporting [70x70/4z] {
xTU7YiL0509GzV__UVlTCbdn1gI-9ot8p4blMEOPAeKPqIOLH8oxKzWORLD1n8gY2k8tXb9XOwG2mugYkwaWOaLH1H7peULltumvbOIi66uG82W1yMjR8AGa
yJF_C_GAfusb512xWMPZQ90TOpRbTpbBaFVzdfu8XhcbdCXKVe8f3mIm2W5QPMOGmnX5WBnoC5vXL8RnoiGhmrGK1OLHeIG41K4P92ZvJ0j98U2LsPAe0A1J
JaP6yIMlZ9zWx_Gh4yQRbd_sZduyOUfXTYkTq38PONfyCo7XPKLSBl-C05eoiafc0hBzPl23xZEBZodgVbZwhYjiJEbxjy6WeH0D1YuiR4hhNmri8417GG5P
xnDHO12J7U81yWe
}

GCPEntityColoring(ErrorReporting)
!define ErrorReporting(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, ErrorReporting, ErrorReporting)
!define ErrorReporting(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, ErrorReporting, ErrorReporting)
