sprite $Logging [70x70/4z] {
xTS5aiD050DHjUv_vsNU-JMZM8L95vgUcNJO8xnB-tnI1J7vxkGRuzCgYAaeZf1yOt1Ii2avGqLnMWKn5SKLn6W-j7oMRynYKhvF30fQD2gEb87npGeLnSFe
K44V4IhZxFFeVUFSMwAlU4121ObG2MOF5JOAyVEihmnD2XMbSrn4GM5trR5eCRket07gABgegA6WWOaKVSQ5CyqmFbFq7T4TCCxPKUHrR1Gr57J8B9htN3YF
qdTTOMDAtxiDHWq5DHXDKTYKrh-QQ21IHr454Ju95HWD9GwwWvu1
}

sprite $LoggingParticipant [50x50/4z] {
pTP50eGm04FH9FU_yxXH_-FP8G_ghVu_wSGK9C4WUOz88CdRHJ28iKW5s4-Sm9zixoqGLqARr29piILP5WPY-m8GgLjsPK06YKZvk8ZRugtpMLpWKl7MVKO8
2L5XdG9ghdEyBAexztipeSMrIQy8PIMYIvnVN7Tb2YGk100GX8WAltXcc3Unlfqz
}


GCPEntityColoring(Logging)
!define Logging(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Logging, Logging)
!define Logging(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Logging, Logging)
