sprite $Monitoring [70x70/4z] {
xTS5TiH030HHTTt_pk4iZo8x5OuUBVxNu-4Qrd-5jsg0C2a58JqI4C8mBGKXYaA72642GXWGc2WAMqj1YAAW8DTX0a8O49We2djBGSX2sRYgJf6UEOH9eyp3
C5QQV_3bok4l31Jeb5Hbk6Wq2bMi5NBuJw1HqYY1lFobwfoPJumSmxwytQF0ULk0fPALSaZ0IRYLKWibXqTxrewLaWtxHBCyp97kjr5cG0cAiJ8OIfeFsreE
zduippQ1ToXrhEnM1iDfi0SxkxsXf0ocZ6DGf7ET44OwxnfC6KhAOCgusaIwgmbXf3kimPHnBKy9J0iCdTGVg7i
}

GCPEntityColoring(Monitoring)
!define Monitoring(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Monitoring, Monitoring)
!define Monitoring(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Monitoring, Monitoring)
