sprite $Profiler [70x70/4z] {
hPW73iCm4CDC_V_HnUfqv5CA2QlZG33nzhe8vwmWe2411mKPCL81GuKY5J0epLcb88FoD5Ga6YfIGqMYeI8rL2GQAbAemcSYcR4gaK5_KAXG54022dSfQ9H1
MVYj9AQWL_RI109V1HVl1qFnkfV50uHivECfEKIgGCI1yhNUmj3rdCeldq4xWaXO5t72youPnVrR-NrrNcPuN-_ECCXObRrx_qbvGzvVxr7OANWAdi8dXGDb
MOfsYWwJEBbBHCdVY-_eUHlbbBo_u2OOzaVoVNTvIZwEM1Rp_XNM0daLrY13zWvZZ8SmKzRY-wk1U4os04m5191W0qCEoJTSs89y7qIwLTNjKDarjtRm1PdM
oQOWqphn5MHQ9-62JEk6e21Jl3dn8ODCWG0IX25hpmC
}

sprite $ProfilerParticipant [50x50/4z] {
bPO7ZWD13CDC___HXsh45uu32IMLuhOfjOAcdg5VEO0CwIEa2fVq6LGHIlf744KewPz1597aqVQMS10kwODG2GVXaZu2KiNrn_NpLdZL_XrNS3mEgZYVE4Gn
jOqL-ZMVh_pAuntWZMsAEQ3k5eaIp3aZakx9TAxx4H4b1CL_efkRg92egkmylcxg5CkrCcB-yQbW0ouPqXMxXS_Fo26ufEQjAlHGpv_Cx437CzmrKQDJJ3vJ
x-G4AL2L4wH0LKwG0hU4V2VZ8L0uueO_
}


!define Profiler(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Profiler, resource)
!define Profiler(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Profiler, resource)
!define ProfilerParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, ProfilerParticipant, ProfilerParticipant)
!define ProfilerParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, ProfilerParticipant, ProfilerParticipant)
