sprite $Trace [70x70/4z] {
xTX5SWH10CH0LVt_qRuPbffaNfqdCeORcEnPEefndKb1ck7b22VJsHIaKPGgIFFWrWedqmfC5AMhAKYZA5MGvi6jNRZVNDInCcQYA1qhOwRRIXIb5yYcafM3
noVJimH4KweW3QJdtJeLHlMoA4hxWvGe2euIGGdqF2060e8YC1XAC9ZX_vNRtJuLE51uAziAxtCKDXKC9LoqfN1PkbwaUPrmCj9yrs0mb60m64kRI6iruMIa
DQp1O2pBWy0OcnxX7_G2
}

GCPEntityColoring(Trace)
!define Trace(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, Trace, Trace)
!define Trace(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, Trace, Trace)
